version: "2"

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - errname
    - errorlint
    - goconst
    - godot
    - misspell
    - noctx
    - predeclared
    - revive
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign

formatters:
  enable:
    - gofumpt

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
