version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: pipelock
    main: ./cmd/pipelock
    binary: pipelock
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/luckyPipewrench/pipelock/internal/cli.Version={{.Version}}
      - -X github.com/luckyPipewrench/pipelock/internal/cli.BuildDate={{.Date}}
      - -X github.com/luckyPipewrench/pipelock/internal/cli.GitCommit={{.ShortCommit}}
      - -X github.com/luckyPipewrench/pipelock/internal/cli.GoVersion={{.Env.GOVERSION}}
      - -X github.com/luckyPipewrench/pipelock/internal/proxy.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: luckyPipewrench
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: "https://github.com/luckyPipewrench/pipelock"
    description: "Security harness for AI agents"
    license: "Apache-2.0"
    folder: Formula
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "pipelock"
    test: |
      system "#{bin}/pipelock", "version"

dockers:
  - image_templates:
      - "ghcr.io/luckypipewrench/pipelock:{{ .Version }}-amd64"
    ids: [pipelock]
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: Dockerfile.goreleaser

  - image_templates:
      - "ghcr.io/luckypipewrench/pipelock:{{ .Version }}-arm64"
    ids: [pipelock]
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
    goarch: arm64
    dockerfile: Dockerfile.goreleaser

docker_manifests:
  - name_template: "ghcr.io/luckypipewrench/pipelock:{{ .Version }}"
    image_templates:
      - "ghcr.io/luckypipewrench/pipelock:{{ .Version }}-amd64"
      - "ghcr.io/luckypipewrench/pipelock:{{ .Version }}-arm64"

  - name_template: "ghcr.io/luckypipewrench/pipelock:latest"
    image_templates:
      - "ghcr.io/luckypipewrench/pipelock:{{ .Version }}-amd64"
      - "ghcr.io/luckypipewrench/pipelock:{{ .Version }}-arm64"
