coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 2%
    patch:
      default:
        target: 80%
ignore:
  - "tests/ws-helper/**"
comment:
  layout: "reach, diff, files"
