// Copyright 2026 Josh Waldrep
// SPDX-License-Identifier: Apache-2.0

package replaycapture

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

// moduleRoot is the repo root relative to this package directory.
const moduleRoot = "../.."

// TestShippedVerifierAcceptsGallery is the clean-machine proof: it generates the
// gallery, builds the real pipelock-verifier binary, and runs
// `pipelock-verifier audit-packet <dir> --key <pub>` against every packet,
// asserting exit 0. This guards against any change that would make a published
// packet stop verifying with the shipped tool.
func TestShippedVerifierAcceptsGallery(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping verifier-binary integration test in -short mode")
	}

	eng := newTestEngine(t)
	outDir := t.TempDir()
	res, err := eng.Generate(DefaultScenarios(), outDir, "v2.7.0-test", fixedStamp())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	bin := buildVerifier(t)

	for _, p := range res.Packets {
		p := p
		t.Run(p.Scenario.ID, func(t *testing.T) {
			// Test-only: bin is a freshly built trusted binary, args are controlled.
			cmd := exec.CommandContext(t.Context(), bin, "audit-packet", p.PacketDir, "--key", res.SignerKeyHex) //nolint:gosec // controlled test args
			out, runErr := cmd.CombinedOutput()
			if runErr != nil {
				t.Fatalf("verifier rejected %s: %v\n%s", p.Scenario.ID, runErr, out)
			}
		})
	}
}

// buildVerifier compiles cmd/pipelock-verifier to a temp binary and returns its
// path.
func buildVerifier(t *testing.T) string {
	t.Helper()
	bin := filepath.Join(t.TempDir(), "pipelock-verifier")
	// Test-only: compiles a first-party command with a constant package path.
	cmd := exec.CommandContext(t.Context(), "go", "build", "-o", bin, "./cmd/pipelock-verifier") //nolint:gosec // controlled test build
	cmd.Dir = moduleRoot
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("build verifier: %v\n%s", err, out)
	}
	return bin
}

// TestCommittedGalleryVerifies enforces launch gates #8 and #10 on the
// checked-in example fixture: every committed packet still verifies (library
// mirror of the shipped verifier) and the fixture lints clean. If someone
// hand-edits a committed packet or a private detail creeps in, this fails.
//
// Core ships ONE minimal verifiable fixture (gate #8: a checked-in example
// packet). The full multi-scenario gallery is generated by the CLI and
// published with the playback UI on the marketing site, not committed here.
func TestCommittedGalleryVerifies(t *testing.T) {
	t.Parallel()

	galleryDir := filepath.Join(moduleRoot, "examples", "playground-replay")
	keyBytes, err := os.ReadFile(filepath.Clean(filepath.Join(galleryDir, artifactSignerKeyName)))
	if err != nil {
		t.Skipf("no committed gallery to verify: %v", err)
	}
	key := trimKey(string(keyBytes))

	if err := LintGalleryFailClosed(galleryDir, nil); err != nil {
		t.Errorf("committed gallery failed linter: %v", err)
	}

	entries, err := os.ReadDir(galleryDir)
	if err != nil {
		t.Fatalf("reading committed gallery: %v", err)
	}
	var packets int
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		dir := filepath.Join(galleryDir, e.Name())
		if _, statErr := os.Stat(filepath.Join(dir, artifactPacketName)); statErr != nil {
			continue
		}
		packets++
		if err := VerifyPacketDir(dir, key); err != nil {
			t.Errorf("committed packet %s failed verification: %v", e.Name(), err)
		}
	}
	if packets < 1 {
		t.Errorf("expected at least one committed fixture packet, found %d", packets)
	}
}

func trimKey(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' || s[i] == '\r' || s[i] == ' ' || s[i] == '\t' {
			continue
		}
		out = append(out, s[i])
	}
	return string(out)
}
