// Copyright 2026 Josh Waldrep
// SPDX-License-Identifier: Apache-2.0

package mcp

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"io"
	"sync"
	"sync/atomic"
	"time"

	"github.com/luckyPipewrench/pipelock/internal/config"
	"github.com/luckyPipewrench/pipelock/internal/mcp/tools"
	"github.com/luckyPipewrench/pipelock/internal/session"
)

const (
	maxMCPListenerClients             = 4096
	listenerPrincipalIdleTTL          = 24 * time.Hour
	listenerLegacyIdleTTL             = 24 * time.Hour
	listenerDegradationReportInterval = time.Minute
	listenerToolDriftRemediation      = "have an authorized operator create the owner-only control file configured by mcp_tool_scanning.listener_drift_reset_file, then request tools/list to re-baseline this listener"
)

const listenerSessionTokenHeader = "Pipelock-Session-Token"

// mcpListenerClientState holds the mutable MCP state that belongs to one
// listener client. token is generated by Pipelock after a successful setup
// flow; Mcp-Session-Id remains protocol routing data and never selects this
// state.
type mcpListenerClientState struct {
	token        string
	key          string
	principalSet string
	principal    bool
	baseline     *tools.ToolBaseline
	recorder     session.Recorder
	lastAccessed uint64
	lastActive   time.Time
	inFlight     atomic.Int64
	commitMu     sync.Mutex
	revoked      atomic.Bool
	done         context.Context
	cancel       context.CancelFunc
}

// mcpListenerPrincipal is an authenticated security identity, not MCP routing
// metadata. key is privacy-safe and stable for the credential identity. An
// exclusive set represents a credential source where only one generation may
// be valid at a time, such as the listener's rotating shared bearer token.
type mcpListenerPrincipal struct {
	key          string
	billingKey   string
	exclusiveSet string
	trust        config.DoWSubjectTrust
}

// mcpListenerClientStates partitions listener state by either a verified
// principal or a legacy Pipelock-issued opaque token. Principal state is
// admitted on the first authenticated request; legacy token state is admitted
// only after a successful initialize response.
//
// The registry retains at most maxMCPListenerClients client states. Legacy
// states keep their compatibility LRU behavior. Principal states are never
// pressure-evicted while live; idle states expire, and admission otherwise
// fails closed at capacity so flooding cannot reset learned security history.
type mcpListenerClientStates struct {
	authMu                  sync.Mutex
	mu                      sync.Mutex
	clients                 map[string]*mcpListenerClientState
	clock                   uint64
	store                   session.Store
	upstreamToolBaseline    *tools.ToolBaseline
	driftEdge               tools.DetectDriftRisingEdge
	degradationReporter     mcpListenerDegradationReporter
	principalSecret         [32]byte
	principalSecretErr      error
	activeBearer            [32]byte
	activeBearerPrincipal   string
	admittedBearerPrincipal string
	hasActiveBearer         bool
	bearerGeneration        uint64
	now                     func() time.Time
	revokeContentionSignal  chan<- struct{}
}

// mcpListenerDegradationReporter aggregates degraded (unbound) requests for one
// listener. It deliberately has no client key: a client that omits the
// Pipelock-issued token is not a trustworthy partition, so keying reporting
// state on anything it supplies would let it allocate unbounded memory. An
// emitted report carries the count since the previous report, so throttling
// reduces volume without losing the evidence that requests ran degraded.
type mcpListenerDegradationReporter struct {
	mu           sync.Mutex
	pending      uint64
	lastReported time.Time
	interval     time.Duration
	now          func() time.Time
}

func newMCPListenerDegradationReporter(interval time.Duration, now func() time.Time) mcpListenerDegradationReporter {
	if interval <= 0 {
		interval = listenerDegradationReportInterval
	}
	if now == nil {
		now = time.Now
	}
	return mcpListenerDegradationReporter{interval: interval, now: now}
}

// observe records one degraded request and reports whether the caller should
// emit. It emits on the first degraded request and then on the first request
// after each interval, returning the count since the last emission. The
// counter saturates rather than wrapping.
func (r *mcpListenerDegradationReporter) observe() (uint64, bool) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.pending != ^uint64(0) {
		r.pending++
	}
	now := r.now()
	if !r.lastReported.IsZero() && now.Sub(r.lastReported) < r.interval {
		return 0, false
	}
	count := r.pending
	r.pending = 0
	r.lastReported = now
	return count, true
}

func newMCPListenerClientStates(store session.Store) *mcpListenerClientStates {
	states := &mcpListenerClientStates{
		clients:              make(map[string]*mcpListenerClientState),
		store:                store,
		upstreamToolBaseline: tools.NewToolBaseline(),
		degradationReporter:  newMCPListenerDegradationReporter(listenerDegradationReportInterval, nil),
		now:                  time.Now,
	}
	_, states.principalSecretErr = rand.Read(states.principalSecret[:])
	return states
}

func (s *mcpListenerClientStates) principal(provider, subject string, epoch uint64) (mcpListenerPrincipal, error) {
	if err := s.ensurePrincipalSecret(); err != nil {
		return mcpListenerPrincipal{}, fmt.Errorf("initialize listener principal key: %w", err)
	}
	if provider == "" || subject == "" {
		return mcpListenerPrincipal{}, nil
	}
	mac := hmac.New(sha256.New, s.principalSecret[:])
	_, _ = mac.Write([]byte(provider))
	_, _ = mac.Write([]byte{0})
	_, _ = mac.Write([]byte(subject))
	_, _ = fmt.Fprintf(mac, "\x00%d", epoch)
	billingMAC := hmac.New(sha256.New, s.principalSecret[:])
	_, _ = billingMAC.Write([]byte("listener-principal-billing-v1\x00"))
	_, _ = billingMAC.Write([]byte(provider))
	_, _ = billingMAC.Write([]byte{0})
	_, _ = billingMAC.Write([]byte(subject))
	return mcpListenerPrincipal{
		key:        fmt.Sprintf("mcp-http-listener-principal:%x", mac.Sum(nil)),
		billingKey: fmt.Sprintf("mcp-http-listener-billing:%x", billingMAC.Sum(nil)),
		trust:      config.DoWTrustPrincipal,
	}, nil
}

func (s *mcpListenerClientStates) bearerPrincipal(subject string) (mcpListenerPrincipal, error) {
	if err := s.ensurePrincipalSecret(); err != nil {
		return mcpListenerPrincipal{}, fmt.Errorf("initialize listener principal key: %w", err)
	}
	fingerprint := hmac.New(sha256.New, s.principalSecret[:])
	_, _ = fingerprint.Write([]byte("listener-bearer-fingerprint-v1\x00"))
	_, _ = fingerprint.Write([]byte(subject))
	var current [32]byte
	copy(current[:], fingerprint.Sum(nil))

	s.mu.Lock()
	defer s.mu.Unlock()
	if !s.hasActiveBearer || !hmac.Equal(s.activeBearer[:], current[:]) {
		s.bearerGeneration++
		s.activeBearer = current
		s.hasActiveBearer = true
	}
	mac := hmac.New(sha256.New, s.principalSecret[:])
	_, _ = mac.Write([]byte("listener-bearer-principal-v1\x00"))
	_, _ = mac.Write(current[:])
	_, _ = fmt.Fprintf(mac, "\x00%d", s.bearerGeneration)
	principal := mcpListenerPrincipal{
		key:          fmt.Sprintf("mcp-http-listener-principal:%x", mac.Sum(nil)),
		billingKey:   s.listenerBearerBillingKey(),
		exclusiveSet: "listener-bearer-v1",
		// One listener bearer identifies a configured agent trust domain, not
		// an individual human/service principal. Every holder intentionally
		// shares the same state and DoW bucket.
		trust: config.DoWTrustAgent,
	}
	s.activeBearerPrincipal = principal.key
	return principal, nil
}

func (s *mcpListenerClientStates) ensurePrincipalSecret() error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.principalSecretErr == nil {
		return nil
	}
	_, s.principalSecretErr = rand.Read(s.principalSecret[:])
	return s.principalSecretErr
}

func (s *mcpListenerClientStates) listenerBearerBillingKey() string {
	mac := hmac.New(sha256.New, s.principalSecret[:])
	_, _ = mac.Write([]byte("listener-bearer-billing-v1"))
	return fmt.Sprintf("mcp-http-listener-billing:%x", mac.Sum(nil))
}

func (s *mcpListenerClientStates) stateForToken(token string) (*mcpListenerClientState, bool) {
	if token == "" {
		return nil, false
	}
	key := mcpListenerStateKey(token)
	s.mu.Lock()
	defer s.mu.Unlock()
	state := s.clients[key]
	if state == nil || state.revoked.Load() {
		return nil, false
	}
	s.touchLocked(state)
	return state, true
}

// stateForPrincipal returns the durable state for a verified caller. Unlike
// the legacy setup-token path, the first authenticated request creates state:
// current MCP transports no longer have an initialize exchange on which a
// proxy-private token can depend.
func (s *mcpListenerClientStates) stateForPrincipal(principal mcpListenerPrincipal) (*mcpListenerClientState, bool) {
	if principal.key == "" {
		return nil, false
	}
	s.mu.Lock()
	if principal.exclusiveSet == "listener-bearer-v1" && principal.key != s.activeBearerPrincipal {
		// Authentication and state admission are separate phases. A request
		// authenticated just before a credential rotation must not race the new
		// request and restore the retired credential epoch afterward.
		s.mu.Unlock()
		return nil, false
	}
	var removed []*mcpListenerClientState
	if principal.exclusiveSet != "" {
		if oldKey := s.admittedBearerPrincipal; oldKey != "" && oldKey != principal.key {
			if state := s.clients[oldKey]; state != nil {
				delete(s.clients, oldKey)
				removed = append(removed, state)
			}
			s.admittedBearerPrincipal = ""
		}
	}
	if state := s.clients[principal.key]; state != nil && !state.revoked.Load() {
		if state.principal && state.inFlight.Load() == 0 && !state.lastActive.After(s.now().Add(-listenerPrincipalIdleTTL)) {
			delete(s.clients, principal.key)
			if s.admittedBearerPrincipal == principal.key {
				s.admittedBearerPrincipal = ""
			}
			removed = append(removed, state)
			s.mu.Unlock()
			s.revokeRemoved(removed)
			return s.stateForPrincipal(principal)
		} else {
			s.touchLocked(state)
			s.mu.Unlock()
			s.revokeRemoved(removed)
			return state, true
		}
	}
	if len(s.clients) >= maxMCPListenerClients {
		removed = append(removed, s.purgeExpiredPrincipalsLocked()...)
		removed = append(removed, s.purgeExpiredLegacyLocked()...)
	}
	if len(s.clients) >= maxMCPListenerClients {
		if legacy := s.removeOldestLegacyLocked(); legacy != nil {
			removed = append(removed, legacy)
		}
	}
	if len(s.clients) >= maxMCPListenerClients {
		s.mu.Unlock()
		s.revokeRemoved(removed)
		return nil, false
	}
	state := newMCPListenerClientState("", principal.key)
	state.principalSet = principal.exclusiveSet
	state.principal = true
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(state.key)
	}
	s.touchLocked(state)
	s.clients[state.key] = state
	if principal.exclusiveSet == "listener-bearer-v1" {
		s.admittedBearerPrincipal = principal.key
	}
	s.mu.Unlock()
	s.revokeRemoved(removed)
	return state, true
}

// stateForLegacySession preserves the pre-token listener behavior for narrow
// transport compatibility tests. Production listeners keep
// listenerStateTokenRequired unset and therefore never call this path.
func (s *mcpListenerClientStates) stateForLegacySession(sessionID string) *mcpListenerClientState {
	if sessionID == "" {
		return newMCPListenerTransientState()
	}
	key := mcpListenerStateKey(sessionID)
	s.mu.Lock()
	if state := s.clients[key]; state != nil && !state.revoked.Load() {
		s.touchLocked(state)
		s.mu.Unlock()
		return state
	}
	var removed []*mcpListenerClientState
	if len(s.clients) >= maxMCPListenerClients {
		removed = append(removed, s.purgeExpiredLegacyLocked()...)
		if len(s.clients) >= maxMCPListenerClients {
			if oldest := s.removeOldestLegacyLocked(); oldest != nil {
				removed = append(removed, oldest)
			}
		}
		if len(s.clients) >= maxMCPListenerClients {
			s.mu.Unlock()
			s.revokeRemoved(removed)
			return newMCPListenerTransientState()
		}
	}
	state := newMCPListenerClientState("", key)
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(key)
	}
	s.touchLocked(state)
	s.clients[key] = state
	s.mu.Unlock()
	s.revokeRemoved(removed)
	return state
}

func (s *mcpListenerClientStates) newSetupState() (*mcpListenerClientState, error) {
	token, err := newMCPListenerSessionToken()
	if err != nil {
		return nil, err
	}
	return newMCPListenerClientState(token, mcpListenerStateKey(token)), nil
}

func newMCPListenerTransientState() *mcpListenerClientState {
	return newMCPListenerClientState("", session.NextInvocationKey("mcp-http-listener-transient"))
}

// newUnboundState returns a request-local state container for a client that
// has not presented a Pipelock-issued listener token. It exists only long
// enough to attach scanner evidence, such as an adaptive SignalBlock, to the
// request that produced it. The caller must discard it before the request
// completes: it must never become a cross-request state partition selected by
// an untrusted client header.
func (s *mcpListenerClientStates) newUnboundState() *mcpListenerClientState {
	state := newMCPListenerTransientState()
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(state.key)
	}
	return state
}

// discardUnboundState removes the evidence recorder allocated for a single
// unbound request. This preserves the event emitted for that request without
// retaining a score, baseline, taint, or chain history that a later request
// could join by presenting client-controlled routing data.
func (s *mcpListenerClientStates) discardUnboundState(state *mcpListenerClientState) {
	if state == nil || state.token != "" {
		return
	}
	state.revoke()
	if s.store != nil {
		s.store.Delete(state.key)
	}
}

func newMCPListenerClientState(token, key string) *mcpListenerClientState {
	done, cancel := context.WithCancel(context.Background())
	return &mcpListenerClientState{
		token:    token,
		key:      key,
		baseline: tools.NewToolBaseline(),
		done:     done,
		cancel:   cancel,
	}
}

// requestContext is canceled when the state is evicted or deleted. An already
// forwarded request therefore cannot commit learned state after its token has
// been revoked.
func (state *mcpListenerClientState) requestContext(parent context.Context) (context.Context, func()) {
	if state == nil || state.done == nil {
		return parent, func() {}
	}
	ctx, cancel := context.WithCancel(parent)
	state.inFlight.Add(1)
	stop := context.AfterFunc(state.done, cancel)
	return ctx, func() {
		stop()
		cancel()
		state.inFlight.Add(-1)
	}
}

func (state *mcpListenerClientState) revoke() {
	state.revokeWithContentionSignal(nil)
}

// revokeWithContentionSignal exposes the point where revocation has observed
// an in-flight response commit and must wait for it. Production callers do not
// need the signal; deterministic concurrency tests use it to avoid scheduling
// assumptions.
func (state *mcpListenerClientState) revokeWithContentionSignal(contended chan<- struct{}) {
	if state == nil {
		return
	}
	if !state.commitMu.TryLock() {
		if contended != nil {
			close(contended)
		}
		state.commitMu.Lock()
	}
	defer state.commitMu.Unlock()
	state.revoked.Store(true)
	if state.cancel != nil {
		state.cancel()
	}
}

// commitIfActive linearizes a response-side state commit or downstream write
// against deletion and eviction. If the response wins, revocation waits for
// that commit to finish; if revocation wins, the stale response is discarded.
func (state *mcpListenerClientState) commitIfActive(commit func()) bool {
	if state == nil {
		return false
	}
	state.commitMu.Lock()
	defer state.commitMu.Unlock()
	if state.revoked.Load() {
		return false
	}
	commit()
	return true
}

// admitSetup adds state to the bounded registry. It holds the registry lock
// across lookup, eviction, and recorder creation, so rejected or evicted keys
// cannot leave recorder state behind outside the cap.
func (s *mcpListenerClientStates) admitSetup(state *mcpListenerClientState) bool {
	if state == nil || state.token == "" || state.revoked.Load() {
		return false
	}
	s.mu.Lock()
	if s.clients[state.key] != nil {
		s.mu.Unlock()
		return false
	}
	var removed []*mcpListenerClientState
	if len(s.clients) >= maxMCPListenerClients {
		removed = append(removed, s.purgeExpiredLegacyLocked()...)
		if len(s.clients) >= maxMCPListenerClients {
			if oldest := s.removeOldestLegacyLocked(); oldest != nil {
				removed = append(removed, oldest)
			}
		}
		if len(s.clients) >= maxMCPListenerClients {
			s.mu.Unlock()
			s.revokeRemoved(removed)
			return false
		}
	}
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(state.key)
	}
	s.touchLocked(state)
	s.clients[state.key] = state
	s.mu.Unlock()
	s.revokeRemoved(removed)
	return true
}

func (s *mcpListenerClientStates) forget(token string) {
	if token == "" {
		return
	}
	s.forgetKey(mcpListenerStateKey(token))
}

func (s *mcpListenerClientStates) forgetLegacySession(sessionID string) {
	if sessionID == "" {
		return
	}
	s.forgetKey(mcpListenerStateKey(sessionID))
}

func (s *mcpListenerClientStates) forgetKey(key string) {
	s.mu.Lock()
	state := s.clients[key]
	if state != nil {
		delete(s.clients, key)
		if s.admittedBearerPrincipal == key {
			s.admittedBearerPrincipal = ""
		}
	}
	s.mu.Unlock()
	s.revokeRemoved([]*mcpListenerClientState{state})
}

func (s *mcpListenerClientStates) toolConfig(state *mcpListenerClientState, cfg *tools.ToolScanConfig) *tools.ToolScanConfig {
	if state == nil || cfg == nil ||
		(cfg.Action == "" && cfg.BindingUnknownAction == "" && cfg.BindingNoBaselineAction == "" && !cfg.DetectDrift) {
		return nil
	}
	if s.driftEdge.Observe(cfg.DetectDrift) {
		s.resetDriftState()
	}
	return &tools.ToolScanConfig{
		Baseline:                state.baseline,
		DriftBaseline:           s.upstreamToolBaseline,
		DriftRemediation:        listenerToolDriftRemediation,
		ListenerDriftResetFile:  cfg.ListenerDriftResetFile,
		Action:                  cfg.Action,
		DetectDrift:             cfg.DetectDrift,
		BindingUnknownAction:    cfg.BindingUnknownAction,
		BindingNoBaselineAction: cfg.BindingNoBaselineAction,
		ExtraPoison:             cfg.ExtraPoison,
	}
}

func (s *mcpListenerClientStates) resetDriftState() {
	s.upstreamToolBaseline.ResetDriftState()
}

// resetUpstreamToolDriftStateIfRequested consumes the operator-controlled,
// one-shot reset file before a request reaches the upstream. It resets only
// definition hashes; per-token known-tool binding state remains intact.
func (s *mcpListenerClientStates) resetUpstreamToolDriftStateIfRequested(cfg *tools.ToolScanConfig, logW io.Writer) bool {
	if cfg == nil || !cfg.DetectDrift || cfg.ListenerDriftResetFile == "" || !consumeToolDriftResetFile(cfg.ListenerDriftResetFile, logW) {
		return false
	}
	s.resetDriftState()
	return true
}

func (s *mcpListenerClientStates) touchLocked(state *mcpListenerClientState) {
	s.clock++
	state.lastAccessed = s.clock
	state.lastActive = s.now()
}

func (s *mcpListenerClientStates) purgeExpiredPrincipalsLocked() []*mcpListenerClientState {
	cutoff := s.now().Add(-listenerPrincipalIdleTTL)
	var removed []*mcpListenerClientState
	for key, state := range s.clients {
		if !state.principal || state.inFlight.Load() != 0 || state.lastActive.After(cutoff) {
			continue
		}
		delete(s.clients, key)
		if s.admittedBearerPrincipal == key {
			s.admittedBearerPrincipal = ""
		}
		removed = append(removed, state)
	}
	return removed
}

func (s *mcpListenerClientStates) purgeExpiredLegacyLocked() []*mcpListenerClientState {
	cutoff := s.now().Add(-listenerLegacyIdleTTL)
	var removed []*mcpListenerClientState
	for key, state := range s.clients {
		if state.principal || state.inFlight.Load() != 0 || state.lastActive.After(cutoff) {
			continue
		}
		delete(s.clients, key)
		removed = append(removed, state)
	}
	return removed
}

func (s *mcpListenerClientStates) removeOldestLegacyLocked() *mcpListenerClientState {
	var oldestKey string
	var oldest uint64
	for key, state := range s.clients {
		if state.principal {
			continue
		}
		if oldestKey == "" || state.lastAccessed < oldest {
			oldestKey = key
			oldest = state.lastAccessed
		}
	}
	if oldestKey != "" {
		state := s.clients[oldestKey]
		delete(s.clients, oldestKey)
		return state
	}
	return nil
}

func (s *mcpListenerClientStates) revokeRemoved(states []*mcpListenerClientState) {
	contentionSignal := s.revokeContentionSignal
	for _, state := range states {
		if state == nil {
			continue
		}
		state.revokeWithContentionSignal(contentionSignal)
		contentionSignal = nil
		if s.store != nil {
			s.store.Delete(state.key)
		}
	}
}

func newMCPListenerSessionToken() (string, error) {
	var raw [32]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("generate MCP listener session token: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(raw[:]), nil
}

func mcpListenerStateKey(sessionID string) string {
	sum := sha256.Sum256([]byte(sessionID))
	return fmt.Sprintf("mcp-http-listener:%x", sum)
}

func listenerAuditSessionKey(sessionID, stateKey string) string {
	if sanitized := sanitizeAuditSessionKey(sessionID); sanitized != "" {
		return sanitized
	}
	sum := sha256.Sum256([]byte(stateKey))
	return fmt.Sprintf("mcp-session:%x", sum[:8])
}
