// Copyright 2026 Josh Waldrep
// SPDX-License-Identifier: Apache-2.0

package mcp

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"sync"
	"sync/atomic"
	"time"

	"github.com/luckyPipewrench/pipelock/internal/mcp/tools"
	"github.com/luckyPipewrench/pipelock/internal/session"
)

const (
	maxMCPListenerClients             = 4096
	listenerDegradationReportInterval = time.Minute
)

const listenerSessionTokenHeader = "Pipelock-Session-Token"

// mcpListenerClientState holds the mutable MCP state that belongs to one
// listener client. token is generated by Pipelock after a successful setup
// flow; Mcp-Session-Id remains protocol routing data and never selects this
// state.
type mcpListenerClientState struct {
	token        string
	key          string
	baseline     *tools.ToolBaseline
	recorder     session.Recorder
	lastAccessed uint64
	commitMu     sync.Mutex
	revoked      atomic.Bool
	done         context.Context
	cancel       context.CancelFunc
}

// mcpListenerClientStates partitions listener state by a Pipelock-issued
// opaque token. A state is admitted only after a successful initialize
// response. Non-setup requests never allocate state.
//
// The registry retains at most maxMCPListenerClients client states. Eviction
// loses only the evicted client's learned state; its next call starts with an
// empty baseline and therefore follows the configured no-baseline action.
type mcpListenerClientStates struct {
	mu                  sync.Mutex
	clients             map[string]*mcpListenerClientState
	clock               uint64
	store               session.Store
	driftEdge           tools.DetectDriftRisingEdge
	degradationReporter mcpListenerDegradationReporter
}

// mcpListenerDegradationReporter aggregates degraded (unbound) requests for one
// listener. It deliberately has no client key: a client that omits the
// Pipelock-issued token is not a trustworthy partition, so keying reporting
// state on anything it supplies would let it allocate unbounded memory. An
// emitted report carries the count since the previous report, so throttling
// reduces volume without losing the evidence that requests ran degraded.
type mcpListenerDegradationReporter struct {
	mu           sync.Mutex
	pending      uint64
	lastReported time.Time
	interval     time.Duration
	now          func() time.Time
}

func newMCPListenerDegradationReporter(interval time.Duration, now func() time.Time) mcpListenerDegradationReporter {
	if interval <= 0 {
		interval = listenerDegradationReportInterval
	}
	if now == nil {
		now = time.Now
	}
	return mcpListenerDegradationReporter{interval: interval, now: now}
}

// observe records one degraded request and reports whether the caller should
// emit. It emits on the first degraded request and then on the first request
// after each interval, returning the count since the last emission. The
// counter saturates rather than wrapping.
func (r *mcpListenerDegradationReporter) observe() (uint64, bool) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if r.pending != ^uint64(0) {
		r.pending++
	}
	now := r.now()
	if !r.lastReported.IsZero() && now.Sub(r.lastReported) < r.interval {
		return 0, false
	}
	count := r.pending
	r.pending = 0
	r.lastReported = now
	return count, true
}

func newMCPListenerClientStates(store session.Store) *mcpListenerClientStates {
	return &mcpListenerClientStates{
		clients:             make(map[string]*mcpListenerClientState),
		store:               store,
		degradationReporter: newMCPListenerDegradationReporter(listenerDegradationReportInterval, nil),
	}
}

func (s *mcpListenerClientStates) stateForToken(token string) (*mcpListenerClientState, bool) {
	if token == "" {
		return nil, false
	}
	key := mcpListenerStateKey(token)
	s.mu.Lock()
	defer s.mu.Unlock()
	state := s.clients[key]
	if state == nil || state.revoked.Load() {
		return nil, false
	}
	s.touchLocked(state)
	return state, true
}

// stateForLegacySession preserves the pre-token listener behavior for narrow
// transport compatibility tests. Production listeners keep
// listenerStateTokenRequired unset and therefore never call this path.
func (s *mcpListenerClientStates) stateForLegacySession(sessionID string) *mcpListenerClientState {
	if sessionID == "" {
		return newMCPListenerTransientState()
	}
	key := mcpListenerStateKey(sessionID)
	s.mu.Lock()
	defer s.mu.Unlock()
	if state := s.clients[key]; state != nil && !state.revoked.Load() {
		s.touchLocked(state)
		return state
	}
	if len(s.clients) >= maxMCPListenerClients {
		s.evictOldestLocked()
	}
	state := newMCPListenerClientState("", key)
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(key)
	}
	s.touchLocked(state)
	s.clients[key] = state
	return state
}

func (s *mcpListenerClientStates) newSetupState() (*mcpListenerClientState, error) {
	token, err := newMCPListenerSessionToken()
	if err != nil {
		return nil, err
	}
	return newMCPListenerClientState(token, mcpListenerStateKey(token)), nil
}

func newMCPListenerTransientState() *mcpListenerClientState {
	return newMCPListenerClientState("", session.NextInvocationKey("mcp-http-listener-transient"))
}

// newUnboundState returns a request-local state container for a client that
// has not presented a Pipelock-issued listener token. It exists only long
// enough to attach scanner evidence, such as an adaptive SignalBlock, to the
// request that produced it. The caller must discard it before the request
// completes: it must never become a cross-request state partition selected by
// an untrusted client header.
func (s *mcpListenerClientStates) newUnboundState() *mcpListenerClientState {
	state := newMCPListenerTransientState()
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(state.key)
	}
	return state
}

// discardUnboundState removes the evidence recorder allocated for a single
// unbound request. This preserves the event emitted for that request without
// retaining a score, baseline, taint, or chain history that a later request
// could join by presenting client-controlled routing data.
func (s *mcpListenerClientStates) discardUnboundState(state *mcpListenerClientState) {
	if state == nil || state.token != "" {
		return
	}
	state.revoke()
	if s.store != nil {
		s.store.Delete(state.key)
	}
}

func newMCPListenerClientState(token, key string) *mcpListenerClientState {
	done, cancel := context.WithCancel(context.Background())
	return &mcpListenerClientState{
		token:    token,
		key:      key,
		baseline: tools.NewToolBaseline(),
		done:     done,
		cancel:   cancel,
	}
}

// requestContext is canceled when the state is evicted or deleted. An already
// forwarded request therefore cannot commit learned state after its token has
// been revoked.
func (state *mcpListenerClientState) requestContext(parent context.Context) (context.Context, func()) {
	if state == nil || state.done == nil {
		return parent, func() {}
	}
	ctx, cancel := context.WithCancel(parent)
	stop := context.AfterFunc(state.done, cancel)
	return ctx, func() {
		stop()
		cancel()
	}
}

func (state *mcpListenerClientState) revoke() {
	state.revokeWithContentionSignal(nil)
}

// revokeWithContentionSignal exposes the point where revocation has observed
// an in-flight response commit and must wait for it. Production callers do not
// need the signal; deterministic concurrency tests use it to avoid scheduling
// assumptions.
func (state *mcpListenerClientState) revokeWithContentionSignal(contended chan<- struct{}) {
	if state == nil {
		return
	}
	if !state.commitMu.TryLock() {
		if contended != nil {
			close(contended)
		}
		state.commitMu.Lock()
	}
	defer state.commitMu.Unlock()
	state.revoked.Store(true)
	if state.cancel != nil {
		state.cancel()
	}
}

// commitIfActive linearizes a response-side state commit or downstream write
// against deletion and eviction. If the response wins, revocation waits for
// that commit to finish; if revocation wins, the stale response is discarded.
func (state *mcpListenerClientState) commitIfActive(commit func()) bool {
	if state == nil {
		return false
	}
	state.commitMu.Lock()
	defer state.commitMu.Unlock()
	if state.revoked.Load() {
		return false
	}
	commit()
	return true
}

// admitSetup adds state to the bounded registry. It holds the registry lock
// across lookup, eviction, and recorder creation, so rejected or evicted keys
// cannot leave recorder state behind outside the cap.
func (s *mcpListenerClientStates) admitSetup(state *mcpListenerClientState) bool {
	if state == nil || state.token == "" || state.revoked.Load() {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.clients[state.key] != nil {
		return false
	}
	if len(s.clients) >= maxMCPListenerClients {
		s.evictOldestLocked()
	}
	if s.store != nil {
		state.recorder = s.store.GetOrCreate(state.key)
	}
	s.touchLocked(state)
	s.clients[state.key] = state
	return true
}

func (s *mcpListenerClientStates) forget(token string) {
	if token == "" {
		return
	}
	s.forgetKey(mcpListenerStateKey(token))
}

func (s *mcpListenerClientStates) forgetLegacySession(sessionID string) {
	if sessionID == "" {
		return
	}
	s.forgetKey(mcpListenerStateKey(sessionID))
}

func (s *mcpListenerClientStates) forgetKey(key string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if state := s.clients[key]; state != nil {
		state.revoke()
		delete(s.clients, key)
		if s.store != nil {
			s.store.Delete(key)
		}
	}
}

func (s *mcpListenerClientStates) toolConfig(state *mcpListenerClientState, cfg *tools.ToolScanConfig) *tools.ToolScanConfig {
	if state == nil || cfg == nil ||
		(cfg.Action == "" && cfg.BindingUnknownAction == "" && cfg.BindingNoBaselineAction == "" && !cfg.DetectDrift) {
		return nil
	}
	if s.driftEdge.Observe(cfg.DetectDrift) {
		s.resetDriftState()
	}
	return &tools.ToolScanConfig{
		Baseline:                state.baseline,
		Action:                  cfg.Action,
		DetectDrift:             cfg.DetectDrift,
		BindingUnknownAction:    cfg.BindingUnknownAction,
		BindingNoBaselineAction: cfg.BindingNoBaselineAction,
		ExtraPoison:             cfg.ExtraPoison,
	}
}

func (s *mcpListenerClientStates) resetDriftState() {
	s.mu.Lock()
	defer s.mu.Unlock()
	for _, state := range s.clients {
		state.baseline.ResetDriftState()
	}
}

func (s *mcpListenerClientStates) touchLocked(state *mcpListenerClientState) {
	s.clock++
	state.lastAccessed = s.clock
}

func (s *mcpListenerClientStates) evictOldestLocked() {
	var oldestKey string
	var oldest uint64
	for key, state := range s.clients {
		if oldestKey == "" || state.lastAccessed < oldest {
			oldestKey = key
			oldest = state.lastAccessed
		}
	}
	if oldestKey != "" {
		state := s.clients[oldestKey]
		state.revoke()
		delete(s.clients, oldestKey)
		if s.store != nil {
			s.store.Delete(oldestKey)
		}
	}
}

func newMCPListenerSessionToken() (string, error) {
	var raw [32]byte
	if _, err := rand.Read(raw[:]); err != nil {
		return "", fmt.Errorf("generate MCP listener session token: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(raw[:]), nil
}

func mcpListenerStateKey(sessionID string) string {
	sum := sha256.Sum256([]byte(sessionID))
	return fmt.Sprintf("mcp-http-listener:%x", sum)
}

func listenerAuditSessionKey(sessionID, stateKey string) string {
	if sanitized := sanitizeAuditSessionKey(sessionID); sanitized != "" {
		return sanitized
	}
	sum := sha256.Sum256([]byte(stateKey))
	return fmt.Sprintf("mcp-session:%x", sum[:8])
}
