//go:build enterprise

// Licensed under the Elastic License 2.0. See enterprise/LICENSE.

package bootstrap

import (
	"fmt"

	"github.com/luckyPipewrench/pipelock/enterprise/conductor/controlplane"
)

// followerConfigYAML renders a complete, validation-clean follower config for
// the generated dev fleet. Every conductor path is the absolute/canonical
// layout path so it passes Conductor's path validation, and the flight
// recorder is enabled with signed checkpoints (mandatory whenever
// conductor.enabled is true). The caller proves loadability via config.Load.
func followerConfigYAML(layout Layout, opts Options, identity controlplane.FollowerIdentity, rootFingerprint string) string {
	return fmt.Sprintf(`# Pipelock follower config for a dev fleet.
# Generated by "pipelock conductor bootstrap" — safe to edit, but the conductor
# paths and the trust-roster root fingerprint are bound to the generated
# material in this directory.
mode: balanced
conductor:
  enabled: true
  conductor_url: %q
  org_id: %q
  fleet_id: %q
  instance_id: %q
  trust_roster_path: %q
  trust_roster_root_fingerprint: %q
  server_ca_file: %q
  client_cert_path: %q
  client_key_path: %q
  bundle_cache_dir: %q
  durable_audit_queue_dir: %q
  audit_signing_key_id: %q
  recorder_key_id: %q
  poll_interval: 30s
  honor_remote_kill_switch: true
  created_skew_seconds: 60
  max_min_version_major_skew: 0
  max_min_version_minor_skew: 1
  max_capability_threshold: 7
  stale_policy:
    grace_multiplier: 1
    after_grace: strict_deny_all
flight_recorder:
  enabled: true
  dir: %q
  sign_checkpoints: true
  redact: true
  checkpoint_interval: 1000
  signing_key_path: %q
`,
		opts.conductorURL(),
		identity.OrgID,
		identity.FleetID,
		identity.InstanceID,
		layout.TrustRosterPath,
		rootFingerprint,
		layout.CACertPath,
		layout.FollowerClientCertPath,
		layout.FollowerClientKeyPath,
		layout.FollowerBundleCacheDir,
		layout.FollowerAuditQueueDir,
		auditKeyID,
		recorderKeyID,
		layout.FollowerRecorderDir,
		layout.FollowerAuditKeyPath,
	)
}
