package cli

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

func generateDockerComposeCmd() *cobra.Command {
	var agentType string
	var output string

	cmd := &cobra.Command{
		Use:   "docker-compose",
		Short: "Generate a Docker Compose file with network isolation",
		Long: `Generate a docker-compose.yaml configured for capability separation.

The agent container is placed on an internal-only network (no internet).
The pipelock container bridges that internal network to the internet,
so all agent web traffic is scanned before leaving the host.

Available agent types:
  generic     - Placeholder agent service you customize (default)
  claude-code - Claude Code CLI in a container
  openhands   - OpenHands (formerly OpenDevin) agent framework

Examples:
  pipelock generate docker-compose
  pipelock generate docker-compose --agent claude-code
  pipelock generate docker-compose --agent openhands -o docker-compose.yaml`,
		RunE: func(_ *cobra.Command, _ []string) error {
			tmpl, err := composeTemplate(agentType)
			if err != nil {
				return err
			}

			if output != "" {
				if err := os.WriteFile(output, []byte(tmpl), 0o644); err != nil { //nolint:gosec // user-requested output file
					return fmt.Errorf("writing compose file: %w", err)
				}
				fmt.Fprintf(os.Stderr, "Docker Compose file written to %s\n", output)
				fmt.Fprintf(os.Stderr, "\nNext steps:\n")
				fmt.Fprintf(os.Stderr, "  1. Generate a pipelock config:  pipelock generate config -o pipelock.yaml\n")
				fmt.Fprintf(os.Stderr, "  2. Create a .env file with your API key:  echo 'ANTHROPIC_API_KEY=sk-ant-...' > .env\n")
				fmt.Fprintf(os.Stderr, "  3. Start the stack:  docker compose up\n")
			} else {
				fmt.Print(tmpl)
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&agentType, "agent", "generic", "agent type: generic, claude-code, openhands")
	cmd.Flags().StringVarP(&output, "output", "o", "", "output file path (default: stdout)")

	return cmd
}

func composeTemplate(agentType string) (string, error) {
	var agentService string

	switch agentType {
	case "generic":
		agentService = genericAgentService()
	case "claude-code":
		agentService = claudeCodeAgentService()
	case "openhands":
		agentService = openhandsAgentService()
	default:
		return "", fmt.Errorf("unknown agent type %q: choose generic, claude-code, or openhands", agentType)
	}

	var b strings.Builder
	b.WriteString(composeHeader(agentType))
	b.WriteString(composeNetworks())
	b.WriteString(composeServices())
	b.WriteString(composePipelockService())
	b.WriteString(agentService)
	if agentType == "claude-code" {
		b.WriteString("\nvolumes:\n  claude-cache:\n")
	}
	return b.String(), nil
}

func composeHeader(agentType string) string {
	return fmt.Sprintf(`# Pipelock Docker Compose — %s agent
# Generated by: pipelock generate docker-compose --agent %s
#
# Architecture:
#   agent (has secrets, no internet) → pipelock (no secrets, has internet) → web
#
# Prerequisites:
#   1. pipelock generate config -o pipelock.yaml
#   2. echo 'ANTHROPIC_API_KEY=sk-ant-...' > .env
#   3. docker compose up

`, agentType, agentType)
}

func composeNetworks() string {
	return `networks:
  # Internal network: agent can reach pipelock but NOT the internet.
  # DNS tunneling is also blocked — no external name resolution.
  pipelock-internal:
    internal: true
    driver: bridge

  # External network: pipelock can reach the internet to fetch pages.
  pipelock-external:
    driver: bridge

`
}

func composeServices() string {
	return `services:
`
}

func composePipelockService() string {
	return `  pipelock:
    image: ghcr.io/luckypipewrench/pipelock:latest
    container_name: pipelock
    networks:
      - pipelock-internal
      - pipelock-external
    command: ["run", "--listen", "0.0.0.0:8888", "--config", "/config/pipelock.yaml"]
    volumes:
      - ./pipelock.yaml:/config/pipelock.yaml:ro
    restart: unless-stopped
    healthcheck:
      test: ["/pipelock", "healthcheck"]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3

`
}

func genericAgentService() string {
	return `  agent:
    # Replace with your agent image or build context:
    # image: my-agent:latest
    build: .
    container_name: agent
    networks:
      - pipelock-internal    # Can ONLY reach pipelock — no internet
    environment:
      - PIPELOCK_FETCH_URL=http://pipelock:8888/fetch
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      # Add your agent's env vars here.
      # Secrets are safe — this container has no internet access.
    volumes:
      - ./workspace:/workspace
    depends_on:
      pipelock:
        condition: service_healthy
    restart: unless-stopped
`
}

func claudeCodeAgentService() string {
	return `  claude-code:
    image: node:22-slim
    container_name: claude-code
    stdin_open: true
    tty: true
    working_dir: /workspace
    networks:
      - pipelock-internal    # Can ONLY reach pipelock — no internet
    entrypoint: ["npx", "@anthropic-ai/claude-code"]
    environment:
      - PIPELOCK_FETCH_URL=http://pipelock:8888/fetch
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./workspace:/workspace
      - claude-cache:/root/.npm
    depends_on:
      pipelock:
        condition: service_healthy
    restart: unless-stopped
`
}

func openhandsAgentService() string {
	return `  openhands:
    image: ghcr.io/all-hands-ai/openhands:main
    container_name: openhands
    networks:
      - pipelock-internal    # Can ONLY reach pipelock — no internet
    ports:
      - "3000:3000"
    environment:
      - PIPELOCK_FETCH_URL=http://pipelock:8888/fetch
      - LLM_API_KEY=${ANTHROPIC_API_KEY}
      - SANDBOX_NETWORK_MODE=none
    volumes:
      - ./workspace:/workspace
    depends_on:
      pipelock:
        condition: service_healthy
    restart: unless-stopped
`
}
