package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/luckyPipewrench/pipelock/internal/config"
)

func generateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate config files or deployment manifests",
		Long: `Generate Pipelock config presets or deployment files.

Examples:
  pipelock generate config --preset balanced
  pipelock generate config --preset strict --output pipelock.yaml
  pipelock generate docker-compose --agent claude-code -o docker-compose.yaml`,
	}

	cmd.AddCommand(generateConfigCmd())
	cmd.AddCommand(generateDockerComposeCmd())
	return cmd
}

func generateConfigCmd() *cobra.Command {
	var preset string
	var output string

	cmd := &cobra.Command{
		Use:   "config",
		Short: "Generate a Pipelock config file from a preset",
		Long: `Generate a YAML config file from one of the built-in presets.

Available presets:
  strict    - Agent can only reach allowlisted API domains (airtight)
  balanced  - Capability separation with monitored web browsing (default)
  audit     - Log everything, restrict nothing (evaluation)

Examples:
  pipelock generate config --preset balanced
  pipelock generate config --preset strict --output pipelock.yaml`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			var cfg *config.Config

			switch preset {
			case config.ModeStrict:
				cfg = strictPreset()
			case config.ModeBalanced:
				cfg = config.Defaults()
			case config.ModeAudit:
				cfg = auditPreset()
			default:
				return fmt.Errorf("unknown preset %q: choose strict, balanced, or audit", preset)
			}

			data, err := yaml.Marshal(cfg)
			if err != nil {
				return fmt.Errorf("marshaling config: %w", err)
			}

			header := fmt.Sprintf("# Pipelock config — %s preset\n# Generated by: pipelock generate config --preset %s\n# Docs: https://github.com/luckyPipewrench/pipelock\n\n", preset, preset)

			if output != "" {
				if err := os.WriteFile(output, []byte(header+string(data)), 0o600); err != nil {
					return fmt.Errorf("writing config file: %w", err)
				}
				fmt.Fprintf(os.Stderr, "Config written to %s\n", output)
			} else {
				cmd.Print(header + string(data))
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&preset, "preset", "balanced", "config preset: strict, balanced, audit")
	cmd.Flags().StringVarP(&output, "output", "o", "", "output file path (default: stdout)")

	return cmd
}

func strictPreset() *config.Config {
	cfg := config.Defaults()
	cfg.Mode = config.ModeStrict
	// In strict mode, the fetch proxy enforces the API allowlist
	cfg.FetchProxy.Monitoring.EntropyThreshold = 3.5
	cfg.FetchProxy.Monitoring.MaxURLLength = 500
	cfg.FetchProxy.Monitoring.MaxReqPerMinute = 30
	return cfg
}

func auditPreset() *config.Config {
	cfg := config.Defaults()
	cfg.Mode = config.ModeAudit
	// Audit mode: detect and log everything but never block.
	// All DLP patterns, blocklists, and entropy checks stay active for
	// visibility — enforce=false makes them log-only.
	enforce := false
	cfg.Enforce = &enforce
	cfg.Logging.IncludeAllowed = true
	cfg.Logging.IncludeBlocked = true
	return cfg
}
