// Copyright 2026 Josh Waldrep
// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"regexp"
	"strings"
	"testing"

	"github.com/spf13/cobra"
)

// Sixty-six commands that do real work accepted a positional argument they
// never read and reported success. A path typed without its flag was thrown
// away while the command carried on with a different value, so
// `pipelock claude setup ~/my/config.yaml` installed hooks against a discovered
// config and exited 0.
//
// This is the runnable half of the defect the grouping tests cover. Like those,
// it walks the assembled tree instead of naming commands, because naming them
// individually is what let the gap open in the first place.
//
// A command's Use string is its advertised contract: `scan [path...]` says it
// takes paths, `version` says it takes nothing. The rule here is that a command
// advertising nothing must refuse an argument. Commands that do advertise one
// are out of scope, and cobra is left to whatever constraint they declare.

// flagsMarker matches the conventional `[flags]` or `(flags)` token, which
// advertises flags rather than a positional argument.
var flagsMarker = regexp.MustCompile(`\s*[\[(]flags[\])]`)

var anyTokenAfterName = regexp.MustCompile(`^\S+\s+\S`)

// positionalInUse reports whether a Use string advertises a positional
// argument. This codebase writes them several ways and all of them count:
// `<name>`, `[name]`, `name...`, a `--` separator introducing a wrapped
// command, and a bare uppercase word as in `receipts PATH`.
//
// A flags marker is stripped first. Treating it as a positional would exclude a
// command whose Use is `foo [flags]` from this test entirely, so the one command
// shaped like that would be the one nobody checked. Nothing in the tree is shaped
// that way today; this keeps a future one from slipping through.
func positionalInUse(use string) bool {
	return anyTokenAfterName.MatchString(flagsMarker.ReplaceAllString(use, ""))
}

// runnableCommandsTakingNoArguments returns every executable command whose Use
// string advertises no positional argument.
func runnableCommandsTakingNoArguments(t *testing.T) []*cobra.Command {
	t.Helper()
	var found []*cobra.Command
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			walk(sub)
		}
		switch c.Name() {
		case "help", "completion", "__complete", "__completeNoDesc":
			return // generated by cobra, not by this codebase
		}
		if !c.HasParent() || !c.Runnable() {
			return
		}
		if positionalInUse(c.Use) {
			return
		}
		found = append(found, c)
	}
	walk(rootCmd())
	if len(found) == 0 {
		t.Fatal("found no argument-free commands; the walk is broken, not the tree")
	}
	return found
}

func TestCommandsAdvertisingNoArgumentRejectOne(t *testing.T) {
	commands := runnableCommandsTakingNoArguments(t)
	for _, cmd := range commands {
		path := cmd.CommandPath()
		if cmd.Args == nil {
			t.Errorf("%s: advertises no argument and declares no constraint, so a "+
				"stray one is accepted and silently ignored. Add cobra.NoArgs", path)
			continue
		}
		// Call the constraint the way cobra does.
		if err := cmd.Args(cmd, []string{"zzz_not_a_real_argument"}); err == nil {
			t.Errorf("%s: advertises no argument but accepts one, which means a "+
				"mistyped path is discarded while the command reports success", path)
		}
		// It must still run bare, or the guard has traded a silent success for
		// a broken command.
		if err := cmd.Args(cmd, nil); err != nil {
			t.Errorf("%s: rejected being run with no arguments: %v", path, err)
		}
	}
	t.Logf("checked %d command(s) that advertise no positional argument", len(commands))
}

func TestFlagsMarkerIsNotMistakenForAnArgument(t *testing.T) {
	// The shape that motivated stripping it: a command advertising only flags
	// must still be checked, not excused. The other cases pin the surrounding
	// behaviour so the strip cannot quietly widen.
	for use, want := range map[string]bool{
		"version":                            false,
		"run [flags]":                        false,
		"run (flags)":                        false,
		"scan [path...]":                     true,
		"receipts PATH":                      true,
		"guard [flags] -- COMMAND [ARGS...]": true,
		"proxy [flags] [-- COMMAND]":         true,
	} {
		t.Run(use, func(t *testing.T) {
			if got := positionalInUse(use); got != want {
				t.Errorf("positionalInUse(%q) = %v, want %v", use, got, want)
			}
		})
	}
}

func TestStrayArgumentFailsThroughTheRealCLI(t *testing.T) {
	// The check above inspects the tree. This one drives the binary, because a
	// constraint that is set and never reached is the defect that made the
	// first attempt at the grouping fix inert.
	cases := [][]string{
		{"version", "zzz_not_a_real_argument"},
		{"presets", "zzz_not_a_real_argument"},
		{"rules", "list", "zzz_not_a_real_argument"},
	}
	for _, args := range cases {
		t.Run(strings.Join(args, " "), func(t *testing.T) {
			stdout, stderr, code := runCLI(t, args...)
			if code == 0 {
				t.Errorf("reported success while ignoring the argument.\nstdout: %q", stdout)
			}
			if !strings.Contains(stderr, "unknown command") && !strings.Contains(stderr, "accepts") {
				t.Errorf("did not say what was wrong.\nstderr: %q", stderr)
			}
		})
	}
}
