// Copyright 2026 Josh Waldrep
// SPDX-License-Identifier: Apache-2.0

package generate

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/luckyPipewrench/pipelock/internal/cli/presets"
	"github.com/luckyPipewrench/pipelock/internal/config"
)

// Cmd returns the top-level "generate" command with all subcommands attached.
func Cmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate config files or deployment manifests",
		Long: `Generate Pipelock config presets or deployment files.

Examples:
  pipelock generate config --preset balanced
  pipelock generate config --preset strict --output pipelock.yaml
  pipelock generate docker-compose --agent claude-code -o docker-compose.yaml`,
	}

	cmd.AddCommand(generateConfigCmd())
	cmd.AddCommand(generateDockerComposeCmd())
	cmd.AddCommand(generateMcporterCmd())
	return cmd
}

func generateConfigCmd() *cobra.Command {
	var preset string
	var output string

	cmd := &cobra.Command{
		Use:   "config",
		Short: "Generate a Pipelock config file from a preset",
		Long: `Generate a YAML config file from one of the built-in presets.

Available presets:
  strict        - Agent can only reach allowlisted API domains (airtight)
  balanced      - Capability separation with monitored web browsing (default)
  audit         - Log everything, restrict nothing (evaluation)
  claude-code   - Balanced coding-agent preset with stricter response scanning
  cursor        - Balanced IDE preset with coding domains
  generic-agent - Broad starting point for new agents during tuning
  hostile-model - Strict preset with every defense layer enabled

Examples:
  pipelock generate config --preset balanced
  pipelock generate config --preset strict --output pipelock.yaml`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			data, err := presets.YAML(preset)
			if err != nil {
				return err
			}

			header := fmt.Sprintf("# Pipelock config — %s preset\n# Generated by: pipelock generate config --preset %s\n# Docs: https://github.com/luckyPipewrench/pipelock\n\n", preset, preset)

			if output != "" {
				if err := os.WriteFile(output, []byte(header+string(data)), 0o600); err != nil {
					return fmt.Errorf("writing config file: %w", err)
				}
				cmd.PrintErrf("Config written to %s\n", output)
			} else {
				w := cmd.OutOrStdout()
				_, _ = fmt.Fprint(w, header+string(data))
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&preset, "preset", config.ModeBalanced, presets.FlagHelp)
	cmd.Flags().StringVarP(&output, "output", "o", "", "output file path (default: stdout)")

	return cmd
}
