// Copyright 2026 Pipelock contributors
// SPDX-License-Identifier: Apache-2.0

import {
  cpSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import assert from "node:assert/strict";
import { findPackageRoot } from "./paths.js";

// Parity fixtures are tampered copies of real run evidence, generated by the Go
// conformance suite. Each expect.json states the verdict every verifier must
// reach under the shared parity contract, in directory mode, for each named
// run, and for each file.
const packageRoot = findPackageRoot(import.meta.url);
const CLI = resolve(packageRoot, "dist/src/cli.js");
const PARITY = resolve(packageRoot, "../../conformance/testdata/parity");

// The phrase each error kind puts in a chain report's error text.
const PHRASES: Record<string, string> = {
  outer_chain_broken: "outer_chain_broken",
  action_receipt_chain: "action receipt chain",
  evidence_receipt_chain: "evidence receipt chain",
  session_mismatch: "does not match requested session",
  symlink_refused: "refuse symlink in evidence directory",
};

interface Cell {
  mode: "dir" | "session" | "file";
  target: string;
  keys: string[];
  endorsements: string[];
  allow_unpinned?: boolean;
  valid: boolean;
  findings: { kind: string; session: string }[];
  errors: { session?: string; kind: string }[];
}

interface Expect {
  symlinks: { name: string; target: string }[];
  cells: Cell[];
}

interface ChainReport {
  session?: string;
  valid: boolean;
  error?: string;
}

function pairs(list: { kind: string; session: string }[]): string[] {
  return list.map((f) => `${f.kind} ${f.session}`).sort();
}

function assertErrorNames(error: string | undefined, kinds: string[], label: string): void {
  for (const kind of kinds) {
    const phrase = PHRASES[kind];
    assert.ok(phrase !== undefined, `${label}: unknown error kind ${kind}`);
    assert.ok(error?.includes(phrase), `${label}: error ${String(error)} should name ${kind}`);
  }
  assert.ok(!error?.includes("no receipts"), `${label}: ${String(error)}`);
}

const classes = readdirSync(PARITY, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort();

test("the parity fixture set covers every contract class", () => {
  assert.equal(classes.length, 15, classes.join(" "));
});

test("explicit file paths resolve symlinks before parent traversal", () => {
  const dir = mkdtempSync(join(tmpdir(), "verifier-path-"));
  try {
    const a = join(dir, "a");
    const b = join(dir, "b");
    mkdirSync(a);
    mkdirSync(join(b, "sub"), { recursive: true });
    const name = "evidence-proxy.run.03b13ee13e01e7f770480f62ea42f1fe-0.jsonl";
    const valid = readFileSync(
      resolve(packageRoot, "../../conformance/testdata/run-chains/valid", name),
    );
    const key = resolve(packageRoot, "../../conformance/testdata/run-chains/signer-key.hex");
    const pathA = join(a, name);
    const pathB = join(b, name);
    const link = join(a, "link");
    symlinkSync(join(b, "sub"), link);
    const input = `${link}/../${name}`;
    for (const { aData, bData, wantOK } of [
      { aData: valid, bData: Buffer.from("not-json\n"), wantOK: false },
      { aData: Buffer.from("not-json\n"), bData: valid, wantOK: true },
    ]) {
      writeFileSync(pathA, aData);
      writeFileSync(pathB, bData);
      const r = spawnSync("node", [CLI, "chain", input, "--key", key, "--json"], {
        encoding: "utf8",
      });
      if (wantOK) {
        assert.equal(r.status, 0, `${r.stdout}${r.stderr}`);
        assert.equal((JSON.parse(r.stdout) as ChainReport).valid, true);
      } else {
        assert.notEqual(r.status, 0, `${r.stdout}${r.stderr}`);
        assert.doesNotMatch(r.stdout, /"valid":\s*true/u);
      }
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("directory mode refuses a symlink anywhere on the walked root path", () => {
  const dir = mkdtempSync(join(tmpdir(), "verifier-root-"));
  try {
    const fixtures = resolve(packageRoot, "../../conformance/testdata/run-chains");
    const key = join(fixtures, "signer-key.hex");
    const realEv = join(dir, "a", "ev");
    const otherEv = join(dir, "b", "ev");
    mkdirSync(join(dir, "a"));
    mkdirSync(join(dir, "b", "sub"), { recursive: true });
    cpSync(join(fixtures, "valid"), realEv, { recursive: true });
    cpSync(join(fixtures, "tampered-predecessor"), otherEv, { recursive: true });
    symlinkSync(join(dir, "b", "sub"), join(dir, "a", "link"));
    symlinkSync(realEv, join(dir, "evlink"));
    const run = (target: string) =>
      spawnSync("node", [CLI, "chain", target, "--dir", "--key", key, "--json"], {
        encoding: "utf8",
      });
    const ok = run(realEv);
    assert.equal(ok.status, 0, `positive control: ${ok.stdout}${ok.stderr}`);
    const opened = run(otherEv);
    assert.equal(opened.status, 1, `${opened.stdout}${opened.stderr}`);
    for (const target of [join(dir, "evlink"), `${join(dir, "a", "link")}/../ev`]) {
      const r = run(target);
      assert.equal(r.status, 1, `${target}: ${r.stdout}${r.stderr}`);
      const report = JSON.parse(r.stdout) as ChainReport;
      assert.equal(report.valid, false);
      assert.match(report.error ?? "", /refuse symlink in evidence root path/u);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("an explicit symlink cannot claim a different recorder session", () => {
  const dir = mkdtempSync(join(tmpdir(), "verifier-session-alias-"));
  try {
    const sourceName = "evidence-proxy.run.03b13ee13e01e7f770480f62ea42f1fe-0.jsonl";
    const otherName = "evidence-proxy.run.f7b327337534352a514bd0a256b1d1c0-0.jsonl";
    const source = resolve(packageRoot, "../../conformance/testdata/run-chains/valid", sourceName);
    const key = resolve(packageRoot, "../../conformance/testdata/run-chains/signer-key.hex");
    const matchingAlias = join(dir, sourceName);
    const mismatchedAlias = join(dir, otherName);
    symlinkSync(source, matchingAlias);
    symlinkSync(source, mismatchedAlias);

    const matching = spawnSync("node", [CLI, "chain", matchingAlias, "--key", key, "--json"], {
      encoding: "utf8",
    });
    assert.equal(matching.status, 0, `${matching.stdout}${matching.stderr}`);
    assert.equal((JSON.parse(matching.stdout) as ChainReport).valid, true);

    const mismatched = spawnSync("node", [CLI, "chain", mismatchedAlias, "--key", key, "--json"], {
      encoding: "utf8",
    });
    assert.equal(mismatched.status, 1, `${mismatched.stdout}${mismatched.stderr}`);
    const report = JSON.parse(mismatched.stdout) as ChainReport;
    assert.equal(report.valid, false);
    assert.match(report.error ?? "", /does not match requested session/u);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

for (const name of classes) {
  test(`parity ${name}: every cell reaches the contract verdict`, () => {
    const exp = JSON.parse(readFileSync(join(PARITY, name, "expect.json"), "utf8")) as Expect;
    const dir = mkdtempSync(join(tmpdir(), `parity-${name}-`));
    try {
      cpSync(join(PARITY, name), dir, { recursive: true });
      for (const l of exp.symlinks) symlinkSync(join(dir, l.target), join(dir, l.name));
      for (const cell of exp.cells) {
        const label = `${name} ${cell.mode} ${cell.target} keys=${cell.keys.join("+")} endorsements=${cell.endorsements.length}`;
        const args =
          cell.mode === "file" ? ["chain", join(dir, cell.target)] : ["chain", dir, "--dir"];
        if (cell.mode === "session") args.push("--session-id", cell.target);
        for (const k of cell.keys) args.push("--key", join(dir, k));
        for (const e of cell.endorsements) args.push("--rotation-endorsement", join(dir, e));
        if (cell.allow_unpinned === true) args.push("--allow-unpinned");
        args.push("--json");
        const r = spawnSync("node", [CLI, ...args], { encoding: "utf8" });
        assert.equal(r.status, cell.valid ? 0 : 1, `${label}: ${r.stdout}${r.stderr}`);
        if (!cell.valid) {
          assert.match(r.stderr, /^verification failed: \S/mu, `${label}: silent failure`);
        }
        const report = JSON.parse(r.stdout) as ChainReport & {
          chains?: ChainReport[];
          continuity?: { findings: { kind: string; session: string }[] };
        };
        assert.equal(report.valid, cell.valid, label);
        if (cell.mode === "file") {
          assertErrorNames(
            report.error,
            cell.errors.map((e) => e.kind),
            label,
          );
          if (cell.valid) assert.equal(report.error, undefined, label);
          continue;
        }
        assert.deepEqual(pairs(report.continuity?.findings ?? []), pairs(cell.findings), label);
        const chains = report.chains ?? [];
        if (cell.mode === "session") {
          assert.deepEqual(
            chains.map((c) => c.session),
            [cell.target],
            label,
          );
        }
        for (const e of cell.errors) {
          assert.ok(
            chains.some((c) => c.session === e.session),
            `${label}: no chain ${String(e.session)}`,
          );
        }
        for (const c of chains) {
          const kinds = cell.errors.filter((e) => e.session === c.session).map((e) => e.kind);
          assert.equal(c.valid, kinds.length === 0, `${label}: chain ${String(c.session)}`);
          if (kinds.length > 0) assertErrorNames(c.error, kinds, `${label} ${String(c.session)}`);
        }
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
}

// A single v2 receipt with no pinned key still has its signature checked
// against its declared signer, so an edited receipt fails under
// --allow-unpinned rather than being reported self-consistent.
function runBEvidenceReceipt(className: string, index: number): string {
  const file = join(
    PARITY,
    className,
    "evidence-proxy.run.f7b327337534352a514bd0a256b1d1c0-0.jsonl",
  );
  const receipts = readFileSync(file, "utf8")
    .trim()
    .split("\n")
    .map((l) => JSON.parse(l) as { type: string; detail: unknown })
    .filter((e) => e.type === "evidence_receipt")
    .map((e) => e.detail);
  const receipt = receipts[index < 0 ? receipts.length + index : index];
  assert.ok(receipt !== undefined, `${className}: no evidence receipt ${index}`);
  const dir = mkdtempSync(join(tmpdir(), "parity-receipt-"));
  const out = join(dir, "receipt.json");
  writeFileSync(out, JSON.stringify(receipt));
  return out;
}

test("an unpinned v2 receipt edited after signing fails", () => {
  const honest = spawnSync(
    "node",
    [CLI, "receipt", runBEvidenceReceipt("v2-drop-rehash", 0), "--allow-unpinned"],
    { encoding: "utf8" },
  );
  assert.equal(honest.status, 0, `positive control: ${honest.stdout}${honest.stderr}`);
  const forged = spawnSync(
    "node",
    [CLI, "receipt", runBEvidenceReceipt("v2-forge-rehash", -1), "--allow-unpinned"],
    { encoding: "utf8" },
  );
  assert.equal(forged.status, 1, `forged receipt: ${forged.stdout}${forged.stderr}`);
});
