#!/usr/bin/env bash
# check-python-pins.sh
#
# Scans every requirements*.txt under the repo for the forbidden
# pattern of loose version pins (`>=`, `<=`, `~=`, `>`, `<`, or
# unpinned packages). The repo policy is `==`-with-`--hash` only,
# documented in CONTRIBUTING.md "Python dependencies".
#
# Why: OpenSSF Scorecard's OSV-Scanner has historically over-reported
# vulnerabilities on `>=` ranges. Pinned hashes are unambiguous.
#
# Skips the pip-compile autogenerated header and any line that is a
# comment or blank. Exits non-zero on any violating line, printing
# both file:line and the offending content for fast triage.
#
# requirements*.in files are intentionally NOT scanned; they are the
# human-editable source manifest for pip-compile and may carry loose
# bounds.

set -euo pipefail

# Find every tracked requirements*.txt the repo cares about.
mapfile -t files < <(
  git ls-files \
    'requirements.txt' \
    '*/requirements.txt' \
    'requirements-*.txt' \
    '*/requirements-*.txt' \
    | sort -u
)

if [[ ${#files[@]} -eq 0 ]]; then
  echo "check-python-pins: no requirements*.txt found, nothing to lint"
  exit 0
fi

violations=0

for file in "${files[@]}"; do
  # awk pass:
  #   - skip blank lines
  #   - skip comments (#) and pip-compile metadata
  #   - skip continuation lines starting with --hash=
  #   - skip continuation lines that are just a backslash or hash
  #   - on package lines, require == as the version operator
  while IFS= read -r line_with_no; do
    lineno="${line_with_no%%:*}"
    line="${line_with_no#*:}"

    # Strip leading whitespace, trailing whitespace, and continuation
    # backslashes so the case-pattern match below sees the line content.
    trimmed="$(echo "$line" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*\\$//' | sed 's/[[:space:]]*$//')"

    # Skip empty + comments + hash continuations + flags.
    case "$trimmed" in
      "" ) continue ;;
      \#* ) continue ;;
      --hash=* ) continue ;;
      --* ) continue ;;
    esac

    # If the line has a package spec, it must use ==.
    # A package spec contains alphanumerics + an operator. Lines that
    # are just whitespace+backslash were already trimmed above.
    if [[ "$trimmed" =~ ^[A-Za-z0-9_.-]+[[:space:]]*(==[[:space:]]*[0-9A-Za-z._+!-]+) ]]; then
      continue
    fi

    # Anything else that mentions a comparator on the package spec is a violation.
    if [[ "$trimmed" =~ (\>=|\<=|\~=|\>[^=]|\<[^=]|[A-Za-z0-9_.-]+[[:space:]]*$) ]]; then
      printf 'check-python-pins: %s:%s: forbidden non-== pin: %s\n' "$file" "$lineno" "$trimmed"
      violations=$((violations + 1))
      continue
    fi
  done < <(grep -nv '^[[:space:]]*$' "$file" || true)
done

if [[ $violations -gt 0 ]]; then
  echo ""
  echo "check-python-pins: $violations violation(s). Repo policy is ==-pinned with --hash."
  echo "See CONTRIBUTING.md 'Python dependencies' and regen instructions in"
  echo "testdata/python_verifier_fixture/README.md."
  exit 1
fi

echo "check-python-pins: ${#files[@]} requirements file(s) clean"
