#!/bin/sh
# Copyright 2026 Josh Waldrep
# SPDX-License-Identifier: Apache-2.0
#
# Pipelock playground per-visitor microVM boot entrypoint (Fly.io / Firecracker).
#
# The microVM is the filesystem + visitor-vs-visitor isolation boundary (clean
# image, destroyed per session). This entrypoint adds the EGRESS boundary that
# the microVM does NOT provide for free: it loads the proven kernel owner-match
# rule so the contained agent uid can reach ONLY the in-process Pipelock proxy,
# then PROVES the drop and aborts the VM if it cannot (fail-closed). Pipelock
# stays the egress firewall inside the VM; this rule stops the agent skipping it.
#
# Fail-closed: any step failing exits non-zero, so the machine never serves an
# agent it could not contain. The nft rule is generated by the SHIPPED renderer
# (`print-containment-nft`), never a hand-copied rule, so it cannot drift.
set -eu

AGENT_USER="${PLAYGROUND_AGENT_USER:-pipelock-agent}"
AGENT_UID="${PLAYGROUND_AGENT_UID:-10001}"
PROXY_PORT="${PLAYGROUND_PROXY_PORT:-8888}"
LISTEN="${PLAYGROUND_LISTEN:-0.0.0.0:8080}"
BIN=/usr/local/bin/pipelock-playground-live
TOYAGENT_BIN=/usr/local/bin/pipelock-playground-toyagent
WEBTOOL_BIN=/usr/local/bin/pipelock-playground-webtool
LLM_AGENT_BIN=/usr/local/bin/pipelock-playground-llm-agent
VERIFIER_LINUX=/usr/local/bin/pipelock-verifier-linux
VERIFIER_MACOS=/usr/local/bin/pipelock-verifier-macos
VERIFIER_WINDOWS=/usr/local/bin/pipelock-verifier-windows.exe

log() { printf '[entrypoint] %s\n' "$*" >&2; }

# --- 0. Disable unprivileged user namespaces when the kernel exposes the knob ---
# The LLM agent has a real shell. It does not need user namespaces, and a visitor
# can otherwise use them to become root inside a private namespace and mount
# tmpfs. The local escape probe below remains the authority: if another kernel
# path still permits that behavior, verify-containment fails closed.
if [ -w /proc/sys/kernel/unprivileged_userns_clone ]; then
	log "disabling unprivileged user namespaces"
	sysctl -w kernel.unprivileged_userns_clone=0 >/dev/null
else
	log "kernel.unprivileged_userns_clone sysctl unavailable; local escape probe remains authoritative"
fi

# --- Secrets: env -> tmpfs file, kept out of argv -------------------------------
# Fly delivers secrets as env vars; the server wants file paths so the values
# never land in argv / process listing. Write them 0600 under /run (tmpfs).
SECRET_DIR=/run/playground
mkdir -p "${SECRET_DIR}"
chmod 0700 "${SECRET_DIR}"

ORCH_KEY_ARGS=""
if [ -n "${PLAYGROUND_ORCHESTRATOR_KEY:-}" ]; then
	umask 077
	printf '%s' "${PLAYGROUND_ORCHESTRATOR_KEY}" >"${SECRET_DIR}/orchestrator.key"
	ORCH_KEY_ARGS="--orchestrator-key ${SECRET_DIR}/orchestrator.key"
fi

MODEL_KEY_ARGS=""
if [ -n "${PLAYGROUND_MODEL_KEY:-}" ]; then
	umask 077
	printf '%s' "${PLAYGROUND_MODEL_KEY}" >"${SECRET_DIR}/model.key"
	MODEL_KEY_ARGS="--model-secret-file ${SECRET_DIR}/model.key"
fi

# --- 1. Load the proven owner-match egress rule (shipped renderer) --------------
log "loading containment nft rule (agent uid ${AGENT_UID} -> only 127.0.0.1:${PROXY_PORT})"
"${BIN}" print-containment-nft --agent-uid "${AGENT_UID}" --proxy-port "${PROXY_PORT}" | nft -f -

# --- 2. Prove the drop is live BEFORE serving (fail-closed boot gate) ------------
log "proving containment (aborts the VM if the agent uid can still egress or use local escape surfaces)"
"${BIN}" verify-containment --toyagent-bin "${TOYAGENT_BIN}" --agent-user "${AGENT_USER}"

# --- 3. Per-session serve flags from broker-provided env ------------------------
# The broker sets these PLAYGROUND_* env vars per machine; map the ones present to
# serve flags. This is the env contract with the broker's BaseEnv/sessionEnv
# (cmd/pipelock-playground-broker): keep the names in sync. Secrets (model /
# orchestrator keys) are handled above as 0600 files, never argv.
EXTRA_ARGS=""
add_flag() { # add_flag <flag> <value>; appends only when value is non-empty
	[ -n "$2" ] && EXTRA_ARGS="${EXTRA_ARGS} $1 $2"
	return 0
}
add_flag --code "${PLAYGROUND_CODE:-}"
add_flag --model-base-url "${PLAYGROUND_MODEL_BASE_URL:-}"
add_flag --model "${PLAYGROUND_MODEL:-}"
add_flag --model-max-steps "${PLAYGROUND_MODEL_MAX_STEPS:-}"
add_flag --daily-turn-budget "${PLAYGROUND_DAILY_TURN_BUDGET:-}"
add_flag --session-ttl "${PLAYGROUND_SESSION_TTL:-}"
add_flag --max-messages-per-session "${PLAYGROUND_MAX_MESSAGES:-}"
# The model agent is all-or-nothing (serve rejects --llm-agent-bin without the
# model flags). The public entrypoint also passes --require-model below, so a
# no-model deployment fails honest instead of serving the deterministic agent as
# "live".
if [ -n "${PLAYGROUND_MODEL_BASE_URL:-}" ]; then
	add_flag --llm-agent-bin "${LLM_AGENT_BIN}"
fi

# --- 4. Serve. One session per VM (--concurrency 1); "$@" allows extra overrides. -
log "containment proven; starting server on ${LISTEN}"
# shellcheck disable=SC2086  # word-splitting of ORCH_KEY_ARGS/MODEL_KEY_ARGS/EXTRA_ARGS is intended; secret paths are fixed under /run/playground (no spaces)
exec "${BIN}" serve \
	--self-managed-containment \
	--require-model \
	--listen "${LISTEN}" \
	--proxy-port "${PROXY_PORT}" \
	--concurrency 1 \
	--toyagent-bin "${TOYAGENT_BIN}" \
	--webtool-bin "${WEBTOOL_BIN}" \
	--verifier-bin-linux "${VERIFIER_LINUX}" \
	--verifier-bin-macos "${VERIFIER_MACOS}" \
	--verifier-bin-windows "${VERIFIER_WINDOWS}" \
	${ORCH_KEY_ARGS} \
	${MODEL_KEY_ARGS} \
	${EXTRA_ARGS} \
	"$@"
