// Copyright 2026 Pipelock contributors
// SPDX-License-Identifier: Apache-2.0

//! Parity fixtures are tampered copies of real run evidence, generated by the
//! Go conformance suite. Each `expect.json` states the verdict every verifier
//! must reach under the shared parity contract, in directory mode, for each
//! named run, and for each file.

mod common;

use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn parity_root() -> PathBuf {
    common::repo_root().join("sdk/conformance/testdata/parity")
}

/// The phrase each error kind puts in a chain report's error text.
fn phrase(kind: &str) -> &'static str {
    match kind {
        "outer_chain_broken" => "outer_chain_broken",
        "action_receipt_chain" => "action receipt chain",
        "evidence_receipt_chain" => "evidence receipt chain",
        "session_mismatch" => "does not match requested session",
        "symlink_refused" => "refuse symlink in evidence directory",
        other => panic!("unknown error kind {other}"),
    }
}

fn run_cli(args: &[String]) -> (i32, String, String) {
    let output = Command::new(env!("CARGO_BIN_EXE_pipelock-verifier-rs"))
        .args(args)
        .output()
        .expect("run verifier");
    (
        output.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&output.stdout).to_string(),
        String::from_utf8_lossy(&output.stderr).to_string(),
    )
}

fn copy_dir(src: &Path, dst: &Path) {
    fs::create_dir_all(dst).expect("mkdir");
    for entry in fs::read_dir(src).expect("read fixture") {
        let entry = entry.expect("entry");
        let to = dst.join(entry.file_name());
        if entry.file_type().expect("type").is_dir() {
            copy_dir(&entry.path(), &to);
        } else {
            fs::copy(entry.path(), &to).expect("copy");
        }
    }
}

struct TempDir(PathBuf);

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn pairs(list: &Value) -> Vec<String> {
    let mut out: Vec<String> = list
        .as_array()
        .map(Vec::as_slice)
        .unwrap_or_default()
        .iter()
        .map(|f| {
            format!(
                "{} {}",
                f["kind"].as_str().unwrap_or_default(),
                f["session"].as_str().unwrap_or_default()
            )
        })
        .collect();
    out.sort();
    out
}

fn assert_error_names(error: &Value, kinds: &[&str], label: &str) {
    let error = error.as_str().unwrap_or_default();
    for kind in kinds {
        assert!(
            error.contains(phrase(kind)),
            "{label}: error {error:?} should name {kind}"
        );
    }
    assert!(!error.contains("no receipts"), "{label}: {error}");
}

fn classes() -> Vec<String> {
    let mut out: Vec<String> = fs::read_dir(parity_root())
        .expect("parity fixtures")
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_ok_and(|t| t.is_dir()))
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    out.sort();
    out
}

#[test]
fn the_parity_fixture_set_covers_every_contract_class() {
    assert_eq!(classes().len(), 15, "{:?}", classes());
}

#[test]
fn every_parity_cell_reaches_the_contract_verdict() {
    for name in classes() {
        let exp: Value = serde_json::from_str(
            &fs::read_to_string(parity_root().join(&name).join("expect.json")).expect("expect"),
        )
        .expect("parse expect");
        let dir = TempDir(std::env::temp_dir().join(format!(
            "parity-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        )));
        copy_dir(&parity_root().join(&name), &dir.0);
        for l in exp["symlinks"].as_array().expect("symlinks") {
            std::os::unix::fs::symlink(
                dir.0.join(l["target"].as_str().expect("target")),
                dir.0.join(l["name"].as_str().expect("name")),
            )
            .expect("symlink");
        }
        for cell in exp["cells"].as_array().expect("cells") {
            let mode = cell["mode"].as_str().expect("mode");
            let target = cell["target"].as_str().expect("target");
            let valid = cell["valid"].as_bool().expect("valid");
            let str_list = |key: &str| -> Vec<String> {
                cell[key]
                    .as_array()
                    .expect("list")
                    .iter()
                    .map(|v| v.as_str().expect("string").to_string())
                    .collect()
            };
            let label = format!(
                "{name} {mode} {target} keys={} endorsements={}",
                str_list("keys").join("+"),
                str_list("endorsements").len()
            );
            let mut args = vec!["chain".to_string()];
            if mode == "file" {
                args.push(dir.0.join(target).display().to_string());
            } else {
                args.push(dir.0.display().to_string());
                args.push("--dir".to_string());
            }
            if mode == "session" {
                args.extend(["--session-id".to_string(), target.to_string()]);
            }
            for k in str_list("keys") {
                args.extend(["--key".to_string(), dir.0.join(k).display().to_string()]);
            }
            for e in str_list("endorsements") {
                args.extend([
                    "--rotation-endorsement".to_string(),
                    dir.0.join(e).display().to_string(),
                ]);
            }
            args.push("--json".to_string());
            let (code, stdout, stderr) = run_cli(&args);
            assert_eq!(code, if valid { 0 } else { 1 }, "{label}: {stdout}{stderr}");
            if !valid {
                assert!(
                    stderr
                        .lines()
                        .any(|l| l.starts_with("verification failed: ") && l.len() > 21),
                    "{label}: silent failure: {stderr}"
                );
            }
            let report: Value = serde_json::from_str(&stdout).expect("json report");
            assert_eq!(report["valid"], valid, "{label}");
            let errors = cell["errors"].as_array().expect("errors");
            if mode == "file" {
                let kinds: Vec<&str> = errors
                    .iter()
                    .map(|e| e["kind"].as_str().expect("kind"))
                    .collect();
                assert_error_names(&report["error"], &kinds, &label);
                if valid {
                    assert!(report.get("error").is_none(), "{label}");
                }
                continue;
            }
            assert_eq!(
                pairs(&report["continuity"]["findings"]),
                pairs(&cell["findings"]),
                "{label}"
            );
            let chains = report["chains"].as_array().expect("chains");
            if mode == "session" {
                let sessions: Vec<&str> = chains
                    .iter()
                    .map(|c| c["session"].as_str().unwrap_or_default())
                    .collect();
                assert_eq!(sessions, vec![target], "{label}");
            }
            for e in errors {
                assert!(
                    chains.iter().any(|c| c["session"] == e["session"]),
                    "{label}: no chain {}",
                    e["session"]
                );
            }
            for c in chains {
                let kinds: Vec<&str> = errors
                    .iter()
                    .filter(|e| e["session"] == c["session"])
                    .map(|e| e["kind"].as_str().expect("kind"))
                    .collect();
                assert_eq!(
                    c["valid"].as_bool(),
                    Some(kinds.is_empty()),
                    "{label}: chain {}",
                    c["session"]
                );
                if !kinds.is_empty() {
                    assert_error_names(&c["error"], &kinds, &format!("{label} {}", c["session"]));
                }
            }
        }
    }
}
