// Copyright 2026 Pipelock contributors
// SPDX-License-Identifier: Apache-2.0

//! Parity fixtures are tampered copies of real run evidence, generated by the
//! Go conformance suite. Each `expect.json` states the verdict every verifier
//! must reach under the shared parity contract, in directory mode, for each
//! named run, and for each file.

mod common;

use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

/// The system temp directory with symlinks resolved. An evidence root may not
/// pass through a symlink, and the temp directory does on some platforms
/// (macOS /var is a symlink to /private/var).
fn physical_temp_dir() -> PathBuf {
    fs::canonicalize(std::env::temp_dir()).expect("canonical temp dir")
}

fn parity_root() -> PathBuf {
    common::repo_root().join("sdk/conformance/testdata/parity")
}

/// The phrase each error kind puts in a chain report's error text.
fn phrase(kind: &str) -> &'static str {
    match kind {
        "outer_chain_broken" => "outer_chain_broken",
        "action_receipt_chain" => "action receipt chain",
        "evidence_receipt_chain" => "evidence receipt chain",
        "session_mismatch" => "does not match requested session",
        "symlink_refused" => "refuse symlink in evidence directory",
        other => panic!("unknown error kind {other}"),
    }
}

fn run_cli(args: &[String]) -> (i32, String, String) {
    let output = Command::new(env!("CARGO_BIN_EXE_pipelock-verifier-rs"))
        .args(args)
        .output()
        .expect("run verifier");
    (
        output.status.code().unwrap_or(-1),
        String::from_utf8_lossy(&output.stdout).to_string(),
        String::from_utf8_lossy(&output.stderr).to_string(),
    )
}

fn copy_dir(src: &Path, dst: &Path) {
    fs::create_dir_all(dst).expect("mkdir");
    for entry in fs::read_dir(src).expect("read fixture") {
        let entry = entry.expect("entry");
        let to = dst.join(entry.file_name());
        if entry.file_type().expect("type").is_dir() {
            copy_dir(&entry.path(), &to);
        } else {
            fs::copy(entry.path(), &to).expect("copy");
        }
    }
}

struct TempDir(PathBuf);

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

#[cfg(unix)]
#[test]
fn explicit_file_path_resolves_symlink_before_parent_traversal() {
    use std::os::unix::fs::symlink;

    let unique = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let dir = TempDir(physical_temp_dir().join(format!(
        "parity-operator-path-{}-{unique}",
        std::process::id()
    )));
    let a = dir.0.join("a");
    let b = dir.0.join("b");
    fs::create_dir_all(&a).expect("mkdir a");
    fs::create_dir_all(b.join("sub")).expect("mkdir b/sub");
    let name = "evidence-proxy.run.03b13ee13e01e7f770480f62ea42f1fe-0.jsonl";
    let source = common::repo_root().join("sdk/conformance/testdata/run-chains");
    let valid = fs::read(source.join("valid").join(name)).expect("signed fixture");
    let key = source.join("signer-key.hex").display().to_string();
    let path_a = a.join(name);
    let path_b = b.join(name);
    let link = a.join("link");
    symlink(b.join("sub"), &link).expect("symlink");
    let input = format!("{}/../{name}", link.display());

    for (a_data, b_data, valid_target) in [
        (valid.as_slice(), b"not-json\n".as_slice(), false),
        (b"not-json\n".as_slice(), valid.as_slice(), true),
    ] {
        fs::write(&path_a, a_data).expect("write a");
        fs::write(&path_b, b_data).expect("write b");
        let (code, stdout, stderr) = run_cli(&[
            "chain".to_string(),
            input.clone(),
            "--key".to_string(),
            key.clone(),
            "--json".to_string(),
        ]);
        if valid_target {
            assert_eq!(code, 0, "{stdout}{stderr}");
            assert_eq!(
                serde_json::from_str::<Value>(&stdout).unwrap()["valid"],
                true
            );
        } else {
            assert_ne!(code, 0, "{stdout}{stderr}");
            assert!(!stdout.contains("\"valid\":true"), "{stdout}{stderr}");
        }
    }
}

#[cfg(unix)]
#[test]
fn directory_mode_refuses_symlink_anywhere_on_walked_root_path() {
    use std::os::unix::fs::symlink;

    let unique = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let dir = TempDir(
        physical_temp_dir().join(format!("parity-root-path-{}-{unique}", std::process::id())),
    );
    let source = common::repo_root().join("sdk/conformance/testdata/run-chains");
    let key = source.join("signer-key.hex").display().to_string();
    let real_ev = dir.0.join("a").join("ev");
    let other_ev = dir.0.join("b").join("ev");
    fs::create_dir_all(&real_ev).expect("mkdir a/ev");
    fs::create_dir_all(&other_ev).expect("mkdir b/ev");
    fs::create_dir_all(dir.0.join("b").join("sub")).expect("mkdir b/sub");
    copy_dir(&source.join("valid"), &real_ev);
    copy_dir(&source.join("tampered-predecessor"), &other_ev);
    symlink(dir.0.join("b").join("sub"), dir.0.join("a").join("link")).expect("symlink");
    symlink(&real_ev, dir.0.join("evlink")).expect("symlink");
    let run = |target: String| {
        run_cli(&[
            "chain".to_string(),
            target,
            "--dir".to_string(),
            "--key".to_string(),
            key.clone(),
            "--json".to_string(),
        ])
    };
    let (code, stdout, stderr) = run(real_ev.display().to_string());
    assert_eq!(code, 0, "positive control: {stdout}{stderr}");
    let (code, stdout, stderr) = run(other_ev.display().to_string());
    assert_eq!(code, 1, "{stdout}{stderr}");
    for target in [
        dir.0.join("evlink").display().to_string(),
        format!("{}/../ev", dir.0.join("a").join("link").display()),
    ] {
        let (code, stdout, stderr) = run(target.clone());
        assert_eq!(code, 1, "{target}: {stdout}{stderr}");
        let report: Value = serde_json::from_str(&stdout).expect("json report");
        assert_eq!(report["valid"], false, "{target}");
        assert!(
            report["error"]
                .as_str()
                .unwrap_or_default()
                .contains("refuse symlink in evidence root path"),
            "{target}: {stdout}"
        );
    }
}

#[cfg(unix)]
#[test]
fn directory_mode_walk_matches_the_operating_system() {
    use std::os::unix::fs::symlink;

    let unique = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let dir = TempDir(
        physical_temp_dir().join(format!("parity-root-walk-{}-{unique}", std::process::id())),
    );
    let source = common::repo_root().join("sdk/conformance/testdata/run-chains");
    let key = source.join("signer-key.hex").display().to_string();
    fs::create_dir_all(dir.0.join("s")).expect("mkdir s");
    fs::create_dir_all(dir.0.join("ev")).expect("mkdir ev");
    fs::create_dir_all(dir.0.join("elsewhere").join("ev")).expect("mkdir elsewhere/ev");
    copy_dir(&source.join("valid"), &dir.0.join("ev"));
    copy_dir(
        &source.join("tampered-predecessor"),
        &dir.0.join("elsewhere").join("ev"),
    );
    fs::write(dir.0.join("afile"), b"").expect("write afile");
    // One entry named `s\..` on POSIX, a symlink the open follows.
    symlink("elsewhere", dir.0.join("s\\..")).expect("symlink");
    let run = |target: String| {
        run_cli(&[
            "chain".to_string(),
            target,
            "--dir".to_string(),
            "--key".to_string(),
            key.clone(),
            "--json".to_string(),
        ])
    };
    let (code, stdout, stderr) = run(dir.0.join("ev").display().to_string());
    assert_eq!(code, 0, "positive control: {stdout}{stderr}");

    let target = format!("{}/s\\../ev", dir.0.display());
    let (code, stdout, stderr) = run(target.clone());
    assert_eq!(code, 1, "{target}: {stdout}{stderr}");
    let report: Value = serde_json::from_str(&stdout).expect("json report");
    assert!(
        report["error"]
            .as_str()
            .unwrap_or_default()
            .contains("refuse symlink in evidence root path"),
        "{target}: {stdout}"
    );

    let target = format!("{}/afile/../ev", dir.0.display());
    let (code, stdout, stderr) = run(target.clone());
    assert_eq!(code, 2, "{target}: {stdout}{stderr}");
    assert!(
        format!("{stdout}{stderr}").contains("is not a directory"),
        "{target}: {stdout}{stderr}"
    );
}

fn pairs(list: &Value) -> Vec<String> {
    let mut out: Vec<String> = list
        .as_array()
        .map(Vec::as_slice)
        .unwrap_or_default()
        .iter()
        .map(|f| {
            format!(
                "{} {}",
                f["kind"].as_str().unwrap_or_default(),
                f["session"].as_str().unwrap_or_default()
            )
        })
        .collect();
    out.sort();
    out
}

fn assert_error_names(error: &Value, kinds: &[&str], label: &str) {
    let error = error.as_str().unwrap_or_default();
    for kind in kinds {
        assert!(
            error.contains(phrase(kind)),
            "{label}: error {error:?} should name {kind}"
        );
    }
    assert!(!error.contains("no receipts"), "{label}: {error}");
}

fn classes() -> Vec<String> {
    let mut out: Vec<String> = fs::read_dir(parity_root())
        .expect("parity fixtures")
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_ok_and(|t| t.is_dir()))
        .map(|e| e.file_name().to_string_lossy().to_string())
        .collect();
    out.sort();
    out
}

#[test]
fn the_parity_fixture_set_covers_every_contract_class() {
    assert_eq!(classes().len(), 15, "{:?}", classes());
}

#[test]
fn every_parity_cell_reaches_the_contract_verdict() {
    for name in classes() {
        let exp: Value = serde_json::from_str(
            &fs::read_to_string(parity_root().join(&name).join("expect.json")).expect("expect"),
        )
        .expect("parse expect");
        let dir = TempDir(physical_temp_dir().join(format!(
            "parity-{name}-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        )));
        copy_dir(&parity_root().join(&name), &dir.0);
        for l in exp["symlinks"].as_array().expect("symlinks") {
            std::os::unix::fs::symlink(
                dir.0.join(l["target"].as_str().expect("target")),
                dir.0.join(l["name"].as_str().expect("name")),
            )
            .expect("symlink");
        }
        for cell in exp["cells"].as_array().expect("cells") {
            let mode = cell["mode"].as_str().expect("mode");
            let target = cell["target"].as_str().expect("target");
            let valid = cell["valid"].as_bool().expect("valid");
            let str_list = |key: &str| -> Vec<String> {
                cell[key]
                    .as_array()
                    .expect("list")
                    .iter()
                    .map(|v| v.as_str().expect("string").to_string())
                    .collect()
            };
            let label = format!(
                "{name} {mode} {target} keys={} endorsements={}",
                str_list("keys").join("+"),
                str_list("endorsements").len()
            );
            let mut args = vec!["chain".to_string()];
            if mode == "file" {
                args.push(dir.0.join(target).display().to_string());
            } else {
                args.push(dir.0.display().to_string());
                args.push("--dir".to_string());
            }
            if mode == "session" {
                args.extend(["--session-id".to_string(), target.to_string()]);
            }
            for k in str_list("keys") {
                args.extend(["--key".to_string(), dir.0.join(k).display().to_string()]);
            }
            for e in str_list("endorsements") {
                args.extend([
                    "--rotation-endorsement".to_string(),
                    dir.0.join(e).display().to_string(),
                ]);
            }
            if cell
                .get("allow_unpinned")
                .and_then(serde_json::Value::as_bool)
                .unwrap_or(false)
            {
                args.push("--allow-unpinned".to_string());
            }
            args.push("--json".to_string());
            let (code, stdout, stderr) = run_cli(&args);
            assert_eq!(code, if valid { 0 } else { 1 }, "{label}: {stdout}{stderr}");
            if !valid {
                assert!(
                    stderr
                        .lines()
                        .any(|l| l.starts_with("verification failed: ") && l.len() > 21),
                    "{label}: silent failure: {stderr}"
                );
            }
            let report: Value = serde_json::from_str(&stdout).expect("json report");
            assert_eq!(report["valid"], valid, "{label}");
            let errors = cell["errors"].as_array().expect("errors");
            if mode == "file" {
                let kinds: Vec<&str> = errors
                    .iter()
                    .map(|e| e["kind"].as_str().expect("kind"))
                    .collect();
                assert_error_names(&report["error"], &kinds, &label);
                if valid {
                    assert!(report.get("error").is_none(), "{label}");
                }
                continue;
            }
            assert_eq!(
                pairs(&report["continuity"]["findings"]),
                pairs(&cell["findings"]),
                "{label}"
            );
            let chains = report["chains"].as_array().expect("chains");
            if mode == "session" {
                let sessions: Vec<&str> = chains
                    .iter()
                    .map(|c| c["session"].as_str().unwrap_or_default())
                    .collect();
                assert_eq!(sessions, vec![target], "{label}");
            }
            for e in errors {
                assert!(
                    chains.iter().any(|c| c["session"] == e["session"]),
                    "{label}: no chain {}",
                    e["session"]
                );
            }
            for c in chains {
                let kinds: Vec<&str> = errors
                    .iter()
                    .filter(|e| e["session"] == c["session"])
                    .map(|e| e["kind"].as_str().expect("kind"))
                    .collect();
                assert_eq!(
                    c["valid"].as_bool(),
                    Some(kinds.is_empty()),
                    "{label}: chain {}",
                    c["session"]
                );
                if !kinds.is_empty() {
                    assert_error_names(&c["error"], &kinds, &format!("{label} {}", c["session"]));
                }
            }
        }
    }
}

/// Writes the `index`-th EvidenceReceipt v2 of run B in a parity class to its
/// own file, as a single receipt an operator might hold. A negative index
/// counts from the end.
fn run_b_evidence_receipt(class: &str, index: isize, dir: &Path) -> PathBuf {
    let file = parity_root()
        .join(class)
        .join("evidence-proxy.run.f7b327337534352a514bd0a256b1d1c0-0.jsonl");
    let text = fs::read_to_string(file).expect("read fixture");
    let receipts: Vec<Value> = text
        .lines()
        .map(|l| serde_json::from_str::<Value>(l).expect("entry"))
        .filter(|e| e.get("type").and_then(Value::as_str) == Some("evidence_receipt"))
        .filter_map(|e| e.get("detail").cloned())
        .collect();
    let at = if index < 0 {
        receipts.len() as isize + index
    } else {
        index
    };
    let receipt = &receipts[usize::try_from(at).expect("index in range")];
    let out = dir.join(format!("{class}-receipt.json"));
    fs::write(&out, receipt.to_string()).expect("write receipt");
    out
}

/// A single v2 receipt with no pinned key still has its signature checked
/// against its declared signer, so an edited receipt fails under
/// --allow-unpinned rather than being reported self-consistent.
#[test]
fn unpinned_edited_evidence_receipt_fails() {
    let dir = physical_temp_dir().join(format!("parity-receipt-{}", std::process::id()));
    fs::create_dir_all(&dir).expect("mkdir");
    let honest = run_b_evidence_receipt("v2-drop-rehash", 0, &dir);
    let (code, out, err) = run_cli(&[
        "receipt".to_string(),
        honest.display().to_string(),
        "--allow-unpinned".to_string(),
    ]);
    assert_eq!(code, 0, "positive control: {out}{err}");
    let forged = run_b_evidence_receipt("v2-forge-rehash", -1, &dir);
    let (code, out, err) = run_cli(&[
        "receipt".to_string(),
        forged.display().to_string(),
        "--allow-unpinned".to_string(),
    ]);
    assert_eq!(code, 1, "forged receipt: {out}{err}");
}

#[cfg(unix)]
#[test]
fn receipt_mode_refuses_a_file_named_as_a_directory() {
    let dir = TempDir(physical_temp_dir().join(format!(
        "parity-receipt-trailing-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("clock")
            .as_nanos()
    )));
    fs::create_dir_all(&dir.0).expect("mkdir");
    let file = dir.0.join("receipt.json");
    fs::copy(
        common::repo_root().join("sdk/conformance/testdata/valid-single.json"),
        &file,
    )
    .expect("copy receipt");
    let run = |target: String| {
        run_cli(&[
            "receipt".to_string(),
            target,
            "--allow-unpinned".to_string(),
        ])
    };
    let (code, stdout, stderr) = run(file.display().to_string());
    assert_eq!(code, 0, "positive control: {stdout}{stderr}");
    for target in [
        format!("{}/", file.display()),
        format!("{}/.", file.display()),
    ] {
        let (code, stdout, stderr) = run(target.clone());
        assert_eq!(code, 2, "{target}: {stdout}{stderr}");
        assert!(
            format!("{stdout}{stderr}").contains("Not a directory"),
            "{target}: {stdout}{stderr}"
        );
    }
}
