package gitprotect

import "fmt"

// GeneratePrePushHook returns the content of a pre-push git hook script.
// The hook runs pipelock git scan-diff on the staged changes before
// allowing a push. If pipelock is not found or returns a non-zero exit
// code, the push is blocked (fail-closed).
func GeneratePrePushHook(pipelockBinary, configPath string) string {
	configFlag := ""
	if configPath != "" {
		configFlag = fmt.Sprintf(" --config %q", configPath)
	}

	return fmt.Sprintf(`#!/bin/sh
# Pre-push hook generated by Pipelock
# Scans for secrets in the diff before allowing a push.
# Remove this file to disable: .git/hooks/pre-push

# Fail closed: if pipelock is not found, block the push
if ! command -v %q >/dev/null 2>&1; then
    echo "ERROR: pipelock not found in PATH. Install pipelock or remove this hook."
    echo "       rm .git/hooks/pre-push"
    exit 1
fi

# Get the diff of commits being pushed vs the remote
# For initial pushes, diff against an empty tree
remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000
empty_tree=$(git hash-object -t tree /dev/null)

while read local_ref local_sha remote_ref remote_sha; do
    if [ "$local_sha" = "$z40" ]; then
        # Deleting a branch, nothing to check
        continue
    fi

    if [ "$remote_sha" = "$z40" ]; then
        # New branch, diff against empty tree
        range="$empty_tree..$local_sha"
    else
        range="$remote_sha..$local_sha"
    fi

    if ! git diff "$range" | %q git scan-diff%s; then
        echo ""
        echo "Push blocked: secrets detected in diff."
        echo "Fix the issues above, then try again."
        exit 1
    fi
done

exit 0
`, pipelockBinary, pipelockBinary, configFlag)
}
