// Copyright 2026 Josh Waldrep
// SPDX-License-Identifier: Apache-2.0

package gitprotect

import (
	"fmt"
	"strings"
)

// shellQuote returns a POSIX-safe single-quoted string.
// Any embedded single quotes are handled by ending the quoted segment,
// inserting an escaped single quote, and reopening the quoted segment.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

// GeneratePrePushHook returns the content of a pre-push git hook script.
// The hook runs pipelock git scan-diff on the staged changes before
// allowing a push. If pipelock is not found or returns a non-zero exit
// code, the push is blocked (fail-closed).
func GeneratePrePushHook(pipelockBinary, configPath string) string {
	configFlag := ""
	if configPath != "" {
		configFlag = " --config " + shellQuote(configPath)
	}

	quotedBin := shellQuote(pipelockBinary)

	return fmt.Sprintf(`#!/bin/sh
# Pre-push hook generated by Pipelock
# Scans for secrets in the diff before allowing a push.
# Remove this file to disable: .git/hooks/pre-push

# Fail closed: if pipelock is not found, block the push
if ! command -v %s >/dev/null 2>&1; then
    echo "ERROR: pipelock not found in PATH. Install pipelock or remove this hook."
    echo "       rm .git/hooks/pre-push"
    exit 1
fi

# Get the diff of commits being pushed vs the remote
# For initial pushes, diff against an empty tree
remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000
empty_tree=$(git hash-object -t tree /dev/null)
tmp_diff=$(mktemp "${TMPDIR:-/tmp}/pipelock-diff.XXXXXX") || {
    echo "ERROR: could not create temporary diff file; blocking push."
    exit 1
}
trap 'rm -f "$tmp_diff"' EXIT HUP INT TERM

while read local_ref local_sha remote_ref remote_sha; do
    if [ "$local_sha" = "$z40" ]; then
        # Deleting a branch, nothing to check
        continue
    fi

    if [ "$remote_sha" = "$z40" ]; then
        # New branch, diff against empty tree
        base="$empty_tree"
    else
        base="$remote_sha"
    fi

    if ! git diff --no-ext-diff --no-textconv "$base" "$local_sha" > "$tmp_diff"; then
        echo "ERROR: git diff failed; blocking push."
        exit 1
    fi

    if ! %s git scan-diff%s < "$tmp_diff"; then
        echo ""
        echo "Push blocked: Pipelock could not verify the diff or found secrets."
        echo "Fix the issue above, then try again."
        exit 1
    fi
    : > "$tmp_diff"
done

exit 0
`, quotedBin, quotedBin, configFlag)
}
